- Engine/source/gui/core/guiControl.cpp
Was treating numbers as floats instead of ints, leading to horrific brokenness.
> Fix setExtent

- Engine/source/sim/netEvent.cpp
Replaces part of #1078. Instead of doing manual reference counting, we use a `StrongRefPtr` in this method.
> Use a strong reference instead of more manual reference counting

- Templates/Empty/game/shaders/common/lighting.hlsl
- Templates/Empty/game/shaders/common/lighting/advanced/vectorLightP.hlsl
- Templates/Full/game/shaders/common/lighting.hlsl
- Templates/Full/game/shaders/common/lighting/advanced/vectorLightP.hlsl
Changed ambient for use a factor of light with camera direction, this allow normals on shadowed surfaces.
Before: 
After:
(on behalf of Luis)
> Allow normals on shadowed surfaces

- Engine/source/forest/forestWindEmitter.cpp
- Engine/source/math/mPoint3.h
> Forest wind emitter

- Engine/source/core/stringBuffer.cpp
- Engine/source/core/strings/unicode.cpp
- Engine/source/core/strings/unicode.h
- Engine/source/core/util/str.cpp
- Engine/source/core/util/test/strTest.cpp
- Engine/source/gfx/gFont.cpp
- Engine/source/gfx/gfxDrawUtil.cpp
- Engine/source/gui/controls/guiTextEditCtrl.cpp
- Engine/source/platformWin32/nativeDialogs/fileDialog.cpp
- Engine/source/platformWin32/nativeDialogs/win32MsgBox.cpp
- Engine/source/platformWin32/winConsole.cpp
- Engine/source/platformWin32/winDInputDevice.cpp
- Engine/source/platformWin32/winExec.cpp
- Engine/source/platformWin32/winFileio.cpp
- Engine/source/platformWin32/winFont.cpp
- Engine/source/platformWin32/winRedbook.cpp
- Engine/source/platformWin32/winUser.cpp
- Engine/source/platformWin32/winVolume.cpp
- Engine/source/platformWin32/winWindow.cpp
- Engine/source/windowManager/win32/win32CursorController.cpp
Fixes about 15 actual buffer overflows due to incorrect use of sizeof on UTF16 strings, and provides safer functions to use for static sized buffers. We found that some of these (in fileDialog.cpp) were regularly writing into caller's stack frames.
> Fix buffer overflows

- Engine/source/shaderGen/GLSL/shaderCompGLSL.cpp
Defines were "defining" structure properties out for IN structures sometimes.
example shadergen glsl output where this bug happened to me:
// struct VertexData
// {
//    vec3 position;
//    vec3 normal;
//    vec3 T;
//    vec3 B;
//    vec2 texCoord;
//    vec2 texCoord2;
// } IN;
//
// out vec4 _TEXCOORD2_;
//
// #define texCoord2 OUT_texCoord2
// #define OUT_outVpos _TEXCOORD2_
> Fixed define bug for OpenGL shadergen. 

- Templates/Empty/game/main.cs
- Templates/Empty/game/main.cs.in
- Templates/Full/game/main.cs
- Templates/Full/game/main.cs.in
`displaySplashScreen` doesn't work, meaning nothing appears for ages. So on unix we'll show the canvas immediately even though it looks a little ugly.
> Show the canvas immediately in unix because the splash doesn't work

- Templates/Empty/buildFiles/config/project.conf
- Templates/Full/buildFiles/config/project.conf
It can still be added in the project manager module list as normal, but since it seems deprecated, let's not include it by default.
> Remove default web deployment

- Engine/source/console/simObject.cpp
should probably look into enhancing assertwarn to be able to take a formatted string at some point...
> feedback for *which* namespace is already linked. 

- Engine/source/gfx/gl/gfxGLDevice.cpp
requires defining the TORQUE_NSIGHT_WORKAROUND preprocessor macro
> nvidia nsight debugger support.

- Engine/source/T3D/aiPlayer.cpp
- Engine/source/math/test/mMatrixTest.cpp
- Engine/source/navigation/navPath.cpp
- Engine/source/platform/test/netTest.cpp
- Engine/source/platform/test/platformFileIOTest.cpp
- Engine/source/platform/test/platformTimerTest.cpp
- Engine/source/platform/test/profilerTest.cpp
- Tools/CMake/modules/module_navigation.cmake
- Tools/CMake/modules/module_testing.cmake
- projects.xml
* They are both useful and can easily be turned off.
* Navigation being off by default causes problems with the navmesh editor, which is _included_ by default, but nonfunctional unless the module is included.
* Navigation can kind of be considered a stock feature.
The only problem is that I see no way to do something equivalent with the project generator. We could add `includeModule` to the Templates' default config files, but this won't show up in the manager UI when you create a new project.
> Include navigation and testing modules by default

- Engine/source/console/fileSystemFunctions.cpp
- Engine/source/gui/controls/guiPopUpCtrl.cpp
- Engine/source/gui/controls/guiTreeViewCtrl.cpp
- Engine/source/gui/core/guiControl.cpp
- Engine/source/gui/core/guiTypes.cpp
- Engine/source/gui/core/guiTypes.h
- Engine/source/gui/editor/guiInspector.cpp
- Engine/source/gui/worldEditor/terrainEditor.cpp
- Engine/source/gui/worldEditor/undoActions.cpp
- Engine/source/gui/worldEditor/worldEditor.cpp
- Engine/source/gui/worldEditor/worldEditor.h
- Engine/source/platformWin32/winExec.cpp
I added/fixed some documentation. If it was incorrect documentation it was changed, if there were inconsistencies in variable names I changed them and if something wasn't documented I added it.
> Documentation

- Engine/source/gui/controls/guiTreeViewCtrl.cpp
The console function changed from void to bool, so we
should actually return the value.
Also, the missing return is an error in VS2013.
> return the result value of scrollVisible

- Templates/Empty/game/shaders/common/gl/projectedShadowV.glsl
- Templates/Full/game/shaders/common/gl/projectedShadowV.glsl
Fixes  OpenGL basic lighting no shadows on player #1098
> Fix shadows on Basic Lighting.

- Engine/source/gfx/D3D9/gfxD3D9Cubemap.cpp
similar to opengl, if the textures comprising a cubemap contain mips, it retrieves them, otherwise it generates them.
> cubemap Mip retrieval-DX

- Engine/source/platformWin32/minidump/winStackWalker.h
- Tools/projectGenerator/templates/vc2010_lib_proj.tpl
- Tools/projectGenerator/templates/vc2k8_lib_proj.tpl
This allows minidump support to compile and be setup correctly when the checkbox is checked. The VS lib templates were missing TORQUE_RELEASE in the preprocessor definitions which caused minidump support to not be enabled regardless of a checkbox or not.
> Fix for minidump support

- Engine/source/gui/controls/guiTreeViewCtrl.cpp
(cherry picked from commit adb2513a2461092486e00b5550bf57fb83d0ccac)
When items in the gui tree control are removed it does  not resize the array because it can create a problem with the tree item id's. So it just NULL's out the element. This causes an access violation.
> Added NULL check in function findItemByName.

- Engine/source/platform/types.h
- Engine/source/platformWin32/stdint.h
Add a temporary local copy of stdint.h for VS2008. This is probably the most robust solution right now. It will be removed again next version when we drop VS2008 support.
> Fix VS2008 again again

- Engine/source/gfx/gl/gfxGLDevice.cpp
> opengl error reporting formatting

- Engine/source/console/console.cpp
Con::executef trampoline had mismatched argc values for the high end (caught by @jamesu)
> Con::executef trampoline had mismatched argc values for the high end

- Engine/source/console/simObject.cpp
This reverts commit 8518c85 due to issues that were discovered. The issue remains, and #748 will be reopened to investigate a proper fix.
> Revert "PR for issue #748"

- Engine/source/lighting/advanced/advancedLightBinManager.cpp
When scene has zero lights sources actives, last ```RenderTexTargetBinManager```render target  are used for render. This cause render artifatcs.
Thx @Lopuska for the fix :)
For replicate:
* Remove or hidde all light sources on editor.
> Fix lighting errors when all lights are disabled.

- Engine/source/ts/collada/colladaAppMesh.cpp
typofix for void ColladaAppMesh::lockMesh(F32 t, const MatrixF& objOffset) which was preventing level load.
> typofix for void ColladaAppMesh::lockMesh

- Tools/CMake/torque3d.cmake
Necesary for distribute binaries.
> Fix Linux rpath.

- Templates/Empty/game/tools/shapeEditor/scripts/shapeEditor.ed.cs
- Templates/Full/game/tools/shapeEditor/scripts/shapeEditor.ed.cs
Related to  Object editor lod alteration fails #1135 
If you check script files, use ```%this.getParent( %id );``` but are a invalid method:
```
DefineEngineMethod( GuiControl, getParent, GuiControl*, (),,
"Get the immediate parent control of the control.\n"
"@return The immediate parent GuiControl or 0 if the control is not parented to a GuiControl.\n" )
{
return object->getParent();
}
```
Looks like the correct method is:
```
//FIXME: [rene 11/09/09 - This clashes with GuiControl.getParent(); bad thing; should be getParentItem]
DefineEngineMethod( GuiTreeViewCtrl, getParentItem, S32, (S32 itemId), ,
"Get the parent of a given id in the tree.\n\n"
"@param itemId TreeItemID of item that has a parent we should get.\n"
"@return Id of parent of given item.")
{ …
```
> Fix GuiTreeViewCtrl::getParentItem incorrent use in ShapeEditor script files.

- Engine/source/gui/core/guiCanvas.cpp
Fixes  fullscreen alt+tab erorrs #1250 
```
if (bitDepth > 0)
{
vm.bitDepth = refreshRate; // <- O_o
}
```
> Fix bug on DefineConsoleMethod GuiCanvas::setVideoMode.

- Engine/source/gfx/gl/gfxGLShader.cpp
For reproduce use Opengl with BasicLighting and open Outpost level.
In BL ```autogenConditioners.h``` file are empty, and every GLSL trying to include cause this error.
```
Program shaders/common/postFx/gl/postFxV.glsl: 
GFXGLShader::initShader - Error compiling shader!
Program shaders/common/postFx/hdr/gl/brightPassFilterP.glsl: 0(412) : error C7529: OpenGL does not allow #include directives
```
> Fix GLSL include when file is empty.

- Tools/projectGenerator/btargets/targets.inc
- Tools/projectGenerator/templates/vc2012_activex_proj.tpl
- Tools/projectGenerator/templates/vc2012_csproj.tpl
- Tools/projectGenerator/templates/vc2012_dll_proj.tpl
- Tools/projectGenerator/templates/vc2012_fileRecurse.tpl
- Tools/projectGenerator/templates/vc2012_fileRecurseCSharp.tpl
- Tools/projectGenerator/templates/vc2012_filter.tpl
- Tools/projectGenerator/templates/vc2012_lib_proj.tpl
- Tools/projectGenerator/templates/vc2012_proj.tpl
- Tools/projectGenerator/templates/vc2012_shared.tpl
- Tools/projectGenerator/templates/vc2012_sln.tpl
Files are essentially just copied from the 2010 version with slight
tweaks, works without any warnings or errors.
It prevents having to do the annoying conversion from the VS2010 version every time you regenerate.
Is additional work on projectgenerator even wanted, seeing as there is also the competing cmake build system?
> Add VS2012 support to projectgenerator

- Engine/source/T3D/vehicles/wheeledVehicle.cpp
passes along mAppliedForce found https://github.com/GarageGames/Torque3D/blob/74a05854d56afe15cbc341575b73b3474af18277/Engine/source/T3D/shapeBase.cpp#L1600 like the rest of the classes. mGravityMod  left as an exercise to someone actually working on a vehicle game at present.
> fix for https://github.com/GarageGames/Torque3D/issues/1262 

- Engine/source/forest/editor/forestEditorCtrl.cpp
- Engine/source/forest/editor/forestEditorCtrl.h
- Templates/Empty/game/core/scripts/client/helperfuncs.cs
- Templates/Empty/game/tools/forestEditor/forestEditorGui.cs
- Templates/Empty/game/tools/forestEditor/main.cs
- Templates/Full/game/core/scripts/client/helperfuncs.cs
- Templates/Full/game/tools/forestEditor/forestEditorGui.cs
- Templates/Full/game/tools/forestEditor/main.cs
Fixes #1227. Rebased version of #1279 for merge into 3.7 branch.
> Issue 1227

- Engine/source/core/stream/bitStream.cpp
causes a fatal assertion when bitstream is passed an int value it cannot transmit given the provided bit length, and reports what the value and count were, respectively.
example of the revised output:
..\..\..\Engine\source\core\stream\bitStream.cpp(339,0): {Fatal} - BitStream::writeInt: value out of range: 40/32 (5 bits)
'Spire_DEBUG.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\D3DCompiler_43.dll'
Error, a DecalManager (547a930) isn't properly out of the bins!
Error, a PhysicalZone (b70f240) isn't properly out of the bins!
Error, a EnvVolume (b712780) isn't properly out of the bins!
Error, a TSStatic (b7203c8) isn't properly out of the bins!
> crash out on net stream leaks.

- Engine/source/forest/ts/tsForestItemData.h
See #1287.
> As for the source of the crash, the problem originates in [tsForestItemData.h](https://github.com/GarageGames/Torque3D/blob/b30b5d907623a89ddb812992de1b0c588f0f41cf/Engine/source/forest/ts/tsForestItemData.h#L91). When the shape file is not found, every item gets given an invalid object box. Then, when the forest cell goes to [update its bounds](https://github.com/GarageGames/Torque3D/blob/b30b5d907623a89ddb812992de1b0c588f0f41cf/Engine/source/forest/forestCell.cpp#L180), it tries to update with all these invalid boxes.
>
> If you're missing a shape file, you really don't want a crash, you want a console error, which you do currently get.
> tsForestItemData: default to no bounds instead of crazy bounds

- Templates/Empty/game/core/scripts/client/postFx/default.postfxpreset.cs
- Templates/Empty/game/core/scripts/client/postFx/postFxManager.gui.settings.cs
- Templates/Full/game/core/scripts/client/postFx/default.postfxpreset.cs
- Templates/Full/game/core/scripts/client/postFx/postFxManager.gui.settings.cs
- Templates/Full/game/levels/Outpost.postfxpreset.cs
@Duion see if this fixes #1302 for you. Seems to work fine for me!
Annoyingly, there's no cleanup before running a level-specific `postfxpreset.cs` file, so each of these files have to have settings for _all_ postFX in them, hence the change in the Outpost presets (to turn the vignette off). See #1304.
> Apply vignette settings properly for #1302

- Engine/source/console/console.cpp
- Engine/source/console/console.h
- Engine/source/console/consoleInternal.cpp
Works around the problem of string conversions for integer and float arg values by temporarily creating a string.
> Add workaround for issue #1292

- Engine/source/console/console.h
- Engine/source/platform/profiler.cpp
There's a few more here and there I'll want to get to as soon as I can, but better to have a couple to start with than none.
> Plugging Memory Leaks

- Templates/Full/game/core/scripts/client/lighting/advanced/lightViz.cs
- Templates/Full/game/shaders/common/lighting/advanced/dbgGlowVisualizeP.hlsl
- Templates/Full/game/shaders/common/lighting/advanced/gl/dbgGlowVisualizeP.glsl
- Templates/Full/game/tools/worldEditor/main.cs
pure script and shader, there will be several of these using identical methodology for deferred. displays a given buffer via the
texture[0] = "#glowbuffer"; entry,
passed along to a given shader via the
samplerNames[0] = "glowBuffer";entry
which corresponds to an expected variable name and register.
as much documentation for later as tool
> glow buffer debug visualiser

- Engine/lib/collada/src/dae/daeStringTable.cpp
- Engine/lib/convexDecomp/NvSimpleTypes.h
- Engine/source/core/strings/stringFunctions.h
- Engine/source/core/util/FastDelegate.h
- Engine/source/platform/types.gcc.h
I am building this project on linux, gcc version 4.9.2 (Ubuntu 4.9.2-10ubuntu13), and I was shocked to get more than 20.000 compiler warnings. So I just started to clean some of them.
I plan to add more compiler warning clean commits if this little commits are accepted and merged.
> Fixed some minor compiler warnings on Linux

- Templates/Empty/game/tools/missionAreaEditor/main.cs
- Templates/Empty/game/tools/missionAreaEditor/missionAreaEditorGui.ed.cs
- Templates/Full/game/tools/missionAreaEditor/main.cs
- Templates/Full/game/tools/missionAreaEditor/missionAreaEditorGui.ed.cs
Fixes #1257
The editor didn't test that a mission area actually existed, so when you switched to the editor, it would trigger the crash.
It now tests if there is a mission area when switching to the editor tool, and if there is not, prompts for the creation of a new one, similar to the auto-prompt for creating terrain blocks.
> Fix for issue #1257

- Engine/source/T3D/gameFunctions.cpp
- Engine/source/gfx/gfxDevice.h
- Engine/source/gui/3d/guiTSControl.cpp
- Engine/source/gui/3d/guiTSControl.h
- Engine/source/scene/reflector.cpp
- Engine/source/scene/sceneManager.cpp
Fixes stereo rendering when a display device isn't present, reproducing similar behaviour to before the Oculus DK2 changes.
> Basic fix for stereo rendering without a display device

- Engine/source/console/console.h
Sort struct initialization to match fields declaration avoids a warnings on GCC.
This is a bit tricky, because with this little change I had removed a good amount of warnings, console.h were included almost anywhere.
I have run some demo and all seem to work fine.
> Fixed warning.

- Engine/source/console/consoleTypes.h
First reported https://www.reddit.com/r/gamedev/comments/3bv7oq/torque_3d_37_released_linux_opengl_client/cspvouc
@dottools found the following:
http://lxr.free-electrons.com/source/include/linux/stddef.h#L15 
http://lxr.free-electrons.com/source/include/linux/compiler-gcc4.h#L14
MSDN:
https://msdn.microsoft.com/en-us/library/dz4y9b9a.aspx
> offsetof is actually a standard thing nowadays it would seem

- Engine/source/core/util/str.cpp
- Engine/source/core/util/str.h
Don't call strlen on data that might not be null-terminated
> Remove badly behaved assert

- Engine/source/platform/profiler.cpp
as per remmed out lines in other samples. see https://github.com/GarageGames/Torque3D/issues/1349 for report, and https://gist.github.com/Azaezel/2aafb88cf0d642418051 for result
> fills in profiler timer fallback

- Engine/source/console/engineDoc.cpp
- Engine/source/forest/editor/forestSelectionTool.cpp
- Engine/source/forest/forestCollision.cpp
- Engine/source/forest/forestDataFile.cpp
- Engine/source/forest/forestWindMgr.cpp
- Engine/source/gfx/gfxTextureManager.cpp
- Engine/source/gui/worldEditor/tSelection.h
- Engine/source/materials/materialDefinition.h
Issue found with PVS-Studio:
Many places utilize post-incrementation with iterators, but it's better performance to use pre-incrementation.
Resolved by changing the iter++ instances to ++iter;
> Utilize ++iter rather than iter++ to improve iterator performance.

- Engine/source/T3D/tsStatic.cpp
That should be off by default.
> allowplayerstep lets folks run up sharper angles than normal.

- Engine/source/T3D/aiPlayer.cpp
- Engine/source/console/consoleParser.cpp
- Engine/source/core/stream/fileStream.cpp
- Engine/source/gui/controls/guiListBoxCtrl.cpp
- Engine/source/gui/editor/guiImageList.cpp
- Engine/source/gui/editor/guiInspector.cpp
- Engine/source/gui/editor/guiInspectorTypes.cpp
- Engine/source/gui/editor/guiShapeEdPreview.cpp
- Engine/source/gui/editor/inspector/group.cpp
- Engine/source/gui/editor/inspector/variableInspector.cpp
- Engine/source/gui/worldEditor/guiMissionArea.cpp
- Engine/source/i18n/lang.cpp
- Engine/source/navigation/navMesh.cpp
- Engine/source/navigation/recastPolyList.cpp
- Engine/source/sfx/null/sfxNullDevice.cpp
Issue found with PVS-Studio:
Many instances where we would create a object via a new call, and then check that it was non-null.
This is redundant, as if we ever were in a situation where new failed, we'd be crashing left and right already, so the additional check is wasted processing.
> Removing pointless null-pointer tests for objects created with new

- CMakeLists.txt
it was causing sdl2 INSTALL to attempt to output to  C:/Program Files (x86)/<projectName>/lib windows side, and  /usr/local/lib on linux
> overrides the default CMAKE_INSTALL_PREFIX

- Engine/source/T3D/fx/precipitation.cpp
This fixes the crash in #1044. The cause was the precipitation calling `getContainer()->castRay` after having been hidden (i.e. the container was NULL).
> Stop precipitation from processing ticks when it's hidden

- Engine/source/console/compiler.h
- Engine/source/math/mMatrix.h
- Engine/source/ts/loader/appMesh.h
There were causing a _lot_ of warnings in files that include them.
> Random VS warnings

- Engine/source/math/mEase.h
Issue found with PVS-Studio:
Many instances of a variable being modified inside of a complex operation. This could lead to unintended results depending on the whims of the compiler.
Resolved by restructuring the functions to modify the variable first, then do the rest of the operation.
Also some minor reformatting to be more code-style compliant.
> Cleanup of ease functions operations.

- Engine/source/T3D/aiPlayer.cpp
- Engine/source/T3D/aiPlayer.h
re-use the position of an object we're following (within reason) so we're not constantly regenning a path.
> followobject position caching

- Engine/source/T3D/physics/bullet/btPlayer.cpp
Removes fatal assertion on duplicated object collisions (meshroads, primarily)
> Removes fatal assertion on duplicated object collisions (meshroads, primarily)

- Engine/source/T3D/physics/bullet/btPlayer.cpp
Should note depending on bullet library version, this one may or may not be needed.
> adds minimum displacement check prior to convexSweepTest to avoid NaNs

- Templates/Empty/game/tools/worldEditor/main.cs
- Templates/Full/game/tools/worldEditor/main.cs
Adds a debug toggle for the script-exposed global found https://github.com/GarageGames/Torque3D/blob/c152ae86f3f09b3c1d736954b352723d274582f1/Engine/source/lighting/advanced/advancedLightBinManager.cpp#L168
> "AL: PSSM Cascade Viz" tool-button

- Engine/source/gui/controls/guiTreeViewCtrl.cpp
"when you change some item or remove, it does not resize the array and in that way it create problem with value"
> From Dušan Jocić: early out of treeview entries to prevent crashes

- Engine/source/windowManager/sdl/sdlWindow.cpp
- Templates/Empty/game/core/scripts/client/defaults.cs
- Templates/Full/game/core/scripts/client/defaults.cs
Default scroll speed wasn't delta-modified, so scroll gui controls were very slow when scrolled via mouse wheel.. This corrects the issue.
> SDL mouse wheel speed fix.

- Tools/CMake/torque3d.cmake
(we're talking 5 minutes vs 80, here)
Alternatively, someone more competent at dealing with cmake could look into string concatenation + a switch to expose it as an option for folks that really really want to know about every possible boo-boo.
> -wall leads to incredibly long compile times

- Engine/source/core/util/tVector.h
Like say, if it's crashing out due to being passed a -1, or adding past the end.
> Adds data to vector out of bounds reports

- Engine/source/gfx/gl/gfxGLCircularVolatileBuffer.h
Apparently there's different orders of operation going on per O/S context.
> From @LuisAntonRebollo -stops infinite loop on exit with SDL2+OGL on Win.

- Templates/Empty/game/tools/worldEditor/main.cs
- Templates/Empty/game/tools/worldEditor/scripts/visibilityLayer.ed.cs
- Templates/Full/game/tools/worldEditor/main.cs
- Templates/Full/game/tools/worldEditor/scripts/visibilityLayer.ed.cs
Allows you to see the active collision info for the physics engine.
(Also catches that the glow buffer mode wasn't added to the empty template, apparently?)
> Adds a debug visualization mode for the active physics world.

- Engine/source/platformWin32/winVolume.cpp
- Engine/source/platformWin32/winVolume.h
-triggered during debug only
-still need to expand that to handle bad directories.
> Adds a verifyCompatibility method to the Win32FileSystem to report case-sensitivity issues

- Engine/source/T3D/convexShape.cpp
- Engine/source/T3D/examples/renderMeshExample.cpp
- Engine/source/console/consoleObject.cpp
- Engine/source/gfx/D3D9/pc/gfxPCD3D9Device.cpp
- Engine/source/gui/containers/guiWindowCtrl.cpp
- Engine/source/gui/core/guiControl.cpp
- Engine/source/gui/worldEditor/worldEditor.cpp
- Engine/source/postFx/postEffect.cpp
- Engine/source/renderInstance/renderPrePassMgr.cpp
Issue found by PVS Studio:
Several instances where we utilize a pointer variable without properly testing that they aren't null first.
> Properly testing pointer vars aren't null before using them.

- Engine/source/platformSDL/sdlMsgBox.cpp
like, say, assertfatal, to allow clicking in the popup.
> release the mouse from window constraints when poping up a window prompt

- Engine/lib/convexDecomp/NvRemoveTjunctions.cpp
(Verified with https://github.com/GarageGames/Torque3D/pull/1376 for sub vs2015)
> From Dušan Jocić: convexDecomp vs2015+ compatibility patch

- Engine/source/materials/processedShaderMaterial.cpp
- Engine/source/shaderGen/HLSL/bumpHLSL.cpp
- Engine/source/terrain/hlsl/terrFeatureHLSL.cpp
- Templates/Empty/game/shaders/common/torque.hlsl
- Templates/Full/game/shaders/common/torque.hlsl
Currently the only option in T3D to use compressed normal maps with parallax is DXT3. This allows allows the use of height in the red channel of a dxt5nm.
A test texture set is here http://narivtech.com/downloads/textures_normal.zip
> Fix to allow parallax mapping with dxtnm textures via the red channel.

- Engine/source/console/astNodes.cpp
- Engine/source/console/compiledEval.cpp
- Engine/source/gui/3d/guiTSControl.cpp
- Engine/source/math/mSphere.cpp
- Engine/source/navigation/guiNavEditorCtrl.cpp
- Engine/source/terrain/glsl/terrFeatureGLSL.cpp
- Engine/source/terrain/hlsl/terrFeatureHLSL.cpp
- Engine/source/ts/tsMesh.cpp
Addresses roughly half of the C4189 warnings though the following methodologies:
1) truly unused vars removed
2) vars leading to remmed out code for debugging remmed in turn.
left out:
vars in macros.
>  C4189 warning cleanups

- Engine/source/T3D/lightAnimData.cpp
Corrects light animation to adhere to the brightness level set in the light's params instead of sticking with the default 0-1 brightness range.
> Light animation brightness fix

- Engine/source/math/mRandom.cpp
- Engine/source/math/mRandom.h
32 and 64 bit windows can handle that. 64 bit linux no likey mixing longs and ints.
> U32 MRandomLCG::randI() was using longs

- Templates/Empty/game/tools/base/menuBar/menuBuilder.ed.cs
- Templates/Full/game/tools/base/menuBar/menuBuilder.ed.cs
Fixes it so when using SDL, the editor menubar will correctly react to accelerator commands.
> SDL Menubar accelerator fix

- Tools/CMake/basics.cmake
This fixes CMake NMake build generation to place the exe in the game directory
> CMake NMake fix to place exe in game directory

- Engine/source/environment/scatterSky.cpp
- Engine/source/environment/scatterSky.h
- Templates/Empty/game/shaders/common/gl/scatterSkyV.glsl
- Templates/Empty/game/shaders/common/scatterSkyV.hlsl
- Templates/Full/game/shaders/common/gl/scatterSkyV.glsl
- Templates/Full/game/shaders/common/scatterSkyV.hlsl
I noticed this while working on DX11 stuff, scattersky has unused vertex formats. Thought i would do a separate PR in case it got lost in the DX11 branch
> Removed unused vertex formats from ScatterSky

- Templates/Empty/game/core/scripts/client/audio.cs
- Templates/Full/game/core/scripts/client/audio.cs
This fixes the sfxCompareProvider function in Full and Empty templates to prefer in the following order: FMOD > OpenAL > XAudio > DirectSound
> SfxCompareProvider fix

- Engine/source/environment/waterBlock.cpp
- Engine/source/environment/waterObject.cpp
- Engine/source/environment/waterObject.h
- Engine/source/environment/waterPlane.cpp
- Templates/Empty/game/shaders/common/water/gl/waterBasicV.glsl
- Templates/Full/game/shaders/common/water/gl/waterBasicV.glsl
Colour is sent via a uniform in the pixel shader, this must be old code leftover from a previous water system or something like that. No point sending data that is never used.
> Removed unused vertex colors from GFXWaterVertex

- Engine/source/T3D/trigger.h
Specifically:
* Made update bits constants protected so that derived classes can
use them - especially NextFreeMask! IIRC, most classes make these
constants public, though there's no real reason to.
* Made potentialEnterObject virtual so that derived classes can
substitute their own logic.
This is desirable because I've found that Trigger is nice for doing AI with, but at the moment you can't make a subclass that does anything useful. This would support adding a new class that inherits from Trigger but has AI-specific features.
> Make Trigger friendlier towards inheritance

- Engine/source/T3D/lightBase.cpp
- Engine/source/console/consoleFunctions.cpp
- Engine/source/console/fieldBrushObject.cpp
- Engine/source/environment/editors/guiMeshRoadEditorCtrl.cpp
- Engine/source/gui/core/guiControl.cpp
- Engine/source/gui/worldEditor/terrainEditor.cpp
- Engine/source/sfx/sfxSystem.cpp
- Engine/source/terrain/terrData.cpp
- Engine/source/ts/collada/colladaLights.cpp
- Engine/source/util/settings.cpp
- Engine/source/util/undo.cpp
Moves from using dStrIsEmpty to the new String::isEmpty static function. Keeps things cleaner, consistent, and works with intellisense.
This is the first move to replace usage of the old dStr___ functions for the more standard String namespace approach.
> Replace uses of dStrIsEmpty with new String::isEmpty

- Engine/source/shaderGen/shaderGen.cpp
(MacOSX 32 bit compatibilty errors. was generating 2k+ shader files. may also address  https://github.com/GarageGames/Torque3D/issues/1219)
> cuts the shadergen hashkey generator down from a 64 bit to a 32 bit key.

- Templates/Empty/game/core/parseArgs.cs
- Templates/Empty/game/main.cs
- Templates/Empty/game/main.cs.in
- Templates/Full/game/core/parseArgs.cs
- Templates/Full/game/main.cs
- Templates/Full/game/main.cs.in
playJournal doesn't have two arguments ([reference](https://github.com/GarageGames/Torque3D/blob/2044b2691e1a29fa65d1bdd163f0d834995433ce/Engine/source/app/game.cpp#L179)).
> playJournal fix and removed depcrecated command line options

- Engine/source/shaderGen/GLSL/shaderFeatureGLSL.cpp
cleans up those
0(473) : warning C7050: "objToTangentSpace[0]" might be used before being initialized
0(473) : warning C7050: "objToTangentSpace[1]" might be used before being initialized
0(473) : warning C7050: "objToTangentSpace[2]" might be used before being initialized
warnings.
> ensures opengl texSpaceMat is initialized from the get-go 

- Templates/Full/game/scripts/server/radiusDamage.cs
%distscale can actually end up negative. causes miscalculations for applyimpulse and the like (or even healing if you've hacked in the capacity for negative damage)
> explosion cover miscalc

- Engine/source/gui/worldEditor/worldEditor.cpp
Relatively simple fix, the engine will crash because this code fails to return if the input obj is NULL:
https://github.com/GarageGames/Torque3D/blob/development/Engine/source/gui/worldEditor/worldEditor.cpp#L2834
Same for selectObject.
This stack is generated in unselectObject's case: http://pastebin.com/nUzFJN5u
So it pretty much just attempts to make a call against a NULL pointer if you don't give them a valid ID :) (Try EWorldEditor.unselectObject(0))
As an aside, I fixed my line endings so we don't have spastic messes for commits anymore.
> Fix NULL pointer Crashes in WorldEditor::selectObject & unselectObject

- Engine/source/gfx/gfxDrawUtil.cpp
Fix for this problem https://github.com/GarageGames/Torque3D/issues/1485
> Fix for OpenGL/D3D11 bottom border offset

- Engine/source/renderInstance/renderTexTargetBinManager.cpp
Caused by a wrong target size. (probably it was ok on the very old OpenGL 1.5 version)
Before fix, wrong behaviour:
http://goo.gl/dik7Ia
After fix, all right:
http://goo.gl/IsrckM
> Glow buffer graphic corruption fix on OpenGL.

- Engine/source/navigation/navMesh.cpp
- Engine/source/navigation/navMesh.h
allows us to leverage  .push_back_unique(&foo); and .clear();
(part 1 in a series)
>  mDirtyTiles changed from std::queue to a vector

- Engine/source/T3D/player.cpp
Players scaled after their creation have collision issues with terrain.
Changing this bit of code fixes those issues for downsized players, even
when shrunk to 10% of their original size.
> Fix for collision issues with scaled players

- Engine/source/gfx/gl/gfxGLCircularVolatileBuffer.h
- Engine/source/gfx/gl/gfxGLTextureTarget.cpp
- Engine/source/gfx/gl/gfxGLWindowTarget.cpp
- Engine/source/gfx/gl/gfxGLWindowTarget.h
This resolves some errors related on render targets and other resources which they are never released after creation causing memory leak. It is specific OpenGL fix inside OpenGL render api implementation.
Thank you (:
> ResourceLeakFix for OpenGL

- Engine/source/math/mQuat.h
The old version doesn't have that 2.0f in the return that seems to be needed.
Also added normalizing inside so it can be used directly for not-normalized quaternions too.
> mQuat.h change to fix QuatF::angleBetween

- Engine/source/sfx/fmod/sfxFMODDevice.h
This solves a crash i have personally had under multiple reinstalls of my OS, happened with windows 7, 8.1 and 10. When unloading the fmodex.dll it crashes on Win32DLibrary::close(). I have never been able to reproduce this bug on another computer though :/ . I have even tried a clean re-install disabling my on-board sound in the bios and using a pcie creative card and same thing happens so it's not a sound card driver.
Only thing that solved it was swapping the order that fmod_event and fmodex was dereferenced thus causing the dll to be unloaded.
> Changed order of fmodex library unload.

- Engine/source/gfx/bitmap/gBitmap.cpp
- Engine/source/gfx/gfxTextureManager.cpp
OR spits out quite a few pointless mips for non square textures, which can lead to it triggering that AssertFatal(mNumMipLevels <= c_maxMipLevels, "GBitmap::allocateBitmap: too many miplevels"); entry
> extraneous mipmap generation prune

- Engine/source/windowManager/win32/win32Window.cpp
This part I changed was the OpenGL fullscreen support I wrote 1 year ago to help Luis during his efforts.
I formatted the code following the T3D convention, removed legacy headers and I fixed this problem:
If you have Torque3D configured on Windows using OpenGL renderer.
Try this:
-go to main menu.
-set fullscreen checkbox to on. Doesn't matter for resolution you are using.
-set a lower resolution, don't turn back on windowed mode yet.
-return to windowed mode disabling fullscreen checkbox.
You'll return to windowed mode, however the desktop resolution won't be restored as the original.
> [OpenGL - Win32] This fix a bug during resolution change.

- Engine/source/gui/core/guiControl.cpp
- Engine/source/gui/core/guiControl.h
adds 3 new horizontal relative gui entries for dealing with swapping elements between 4:3 and 16:9 aspect ratios.  "relativeToYL" maintains the initial aspect ratio, keeping the leftmost edge the same, "relativeToYR" also shifts it so the right hand side is shifted over so that edge would match, and "relativeToYC" takes/adds space from both sides
> initial aspect ratio maintaining relative gui scaling

- Engine/source/gfx/gl/sdl/gfxGLDevice.sdl.cpp
- Engine/source/gfx/gl/tGL/tGL.cpp
- Engine/source/gfx/gl/tGL/tGL.h
- Engine/source/platformSDL/sdlPlatformGL.cpp
This allows Torque3D to run on the open source Linux 3D drivers. There are still many issues but with this small patch it at least starts and is semi-functional.
* Explicitly request a GL 3.2 context
* Enable 'experimental' extensions on glew (This appears necessary to get glew to work with explictly set GL versions)
> Fix running on Linux / Intel Mesa drivers

- Engine/source/T3D/rigid.cpp
First line is to ensure similar behavior to current regarding pushback on the object doing the colliding.
Second line applies an impulse to the rigid that was collided with.
> Backend correction for the rigid vs rigid collision resolver:

- Engine/source/platform/platformNet.cpp
SkypeLog: 28.02.2015
[17:18:32] Dušan Jocic: when creating user datagram protocol or UDP, old
implementation was limiting lan utalization to 1% of our modern 1000Mbps
hardwar
[17:19:15] Dušan Jocic: that add proper buffer size for udp socket
[17:19:43] Dušan Jocic: and lift off limitation what was present there
for 10/100 mbps lan
> +proper buffer size for udp socket

- Engine/source/T3D/decal/decalManager.cpp
TorqueScript function to edit the position of decals created with decalManagerAddDecal.
---
Playing with the idea of creating a shadow from script using decals I found:
-Creating and deleting decals with TorqueScript is quite simple with the functions decalManagerAddDecal and decalManagerRemoveDecal.
-But once you create a decal there isn't any scripted way to modify it.
A solution I was thinking on use is to just keep deleting old decals and create a new one in the new position but a problem appeared as the ID of the decal keeps increasing making the c++ internal array of decals bigger.
I fear that may end as a memory leak so I decided to add an edit function.
This function imitates how proyectedshadow works so it's quite standard.
The math at the start is copied from the one used when …
> New script function to edit script-created decals

- Engine/source/ts/collada/colladaShapeLoader.cpp
fixes the loading of cached dts shapes on zip(#1466 ):
if the cached shape is not present, it warns through console and forces it to be cached to disk.
If the dts is present in the archive, it will be used (unless forceDAE) regardless of the creation date, since it was zipped on purpose.
> Fix zipped dts loading

- Engine/source/gfx/gl/gfxGLCardProfiler.cpp
This over-rides the data set here https://github.com/GarageGames/Torque3D/blob/development/Engine/source/gfx/gl/gfxGLEnumTranslate.cpp#L200-L238.
> GL floating point format fix.

- Engine/source/gfx/gfxDevice.cpp
exposes the GFX->beginReset(); method to script to allow folks to force the gbuffer to reinitialize (if, say a custom element is holding on to data in a buffer and it needs a cleaning, to name one example)
> new method: ResetGFX();

- Tools/CMake/CMakeLists.txt
- Tools/CMake/torque3d.cmake
This fixes compiling a release build with MSVC 2015. The issue was that the DirectX runtime requires a function that is no longer present in MSVC 2015. However, Microsoft was nice enough to add a legacy compatibility library to continue using it, so linking against that fixes the linker errors and it works again.
However, we have to check for MSVC 2015, and to do that requires CMake 3.1.4 as that is when they added MSVC14 macro. If that is not okay, I can come up with a solution to keep backwards compatibility, but c'mon its 2016. They are at CMake 3.5.0 now :/
> Fix release build compile with MSVC 2015 (finally)

- Tools/CMake/torque3d.cmake
Makes the cmake SDL flag a regular, non-advanced option so that it's not hidden from the base setup on Windows.
> CMake SDL Option

- Engine/source/gfx/gl/gfxGLEnumTranslate.cpp
Removes some unnecessary extension checks for GL, as those formats are part of 3.2 core. SDL is having some conflicts with extension detection with GL.
> Fix up GL formats to comply with core profile.

- Engine/source/gfx/gfxDrawUtil.cpp
Pretty much round 2 for the same problem here: https://github.com/GarageGames/Torque3D/commit/e3b228db8bf7c34f205724a55505f9294b2c41bf
> DX11/GL border offset fix for GFXDrawUtil::drawRect

- Templates/Full/game/scripts/server/physicsShape.cs
- Templates/Full/game/scripts/server/scriptExec.cs
- Templates/Full/game/scripts/server/shapeBase.cs
Adds in some missing script functions that let projectiles damage and destroy physics shapes.
> Re-enable destruction of PhysicsShapes.

- Engine/source/gfx/gfxTextureProfile.cpp
- Engine/source/gfx/gfxTextureProfile.h
Certain plugins were not playing nice on the directx end with updating rendertargets. Provides a profile for targets intended to be continuously updated.
> GFXDynamicTextureProfile

- Tools/CMake/torque3d.cmake
Fixes the blacklist filter in the event we aren't using SDL to avoid including an unwanted file dialog codefile.
> Fixes the cmake blacklist filter it not using SDL

- Engine/source/T3D/shapeBase.cpp
When attempting to select a camera Object(so going into the editor, going into the freefloating camera and then back to the player camera and selecting the freefloating one) while the material editor was open, it would crash because it attempts to access the shapebase object's shapeInstance - but cameras don't have a shape.
This fixes it so it makes sure there's a shapeinstance before trying to get the material data.
Pertains to #1486
> Select camera when in material editor crashfix.

- Engine/source/math/mBox.h
Box3F::extend only checks the axis once. This is incorrect behaviour for an extend method as for example if we have a point which satisfies both `p.AXIS < minExtents.AXIS` and `p.AXIS > maxExtents.AXIS` only minExtent.AXIS will get set.
This pull request fixes the aforementioned issue.
> Fix axis check in Box3F::extend method

- Engine/source/math/mathUtils.cpp
Epoxy looks to handle the projection depth range so it behaves more like D3D, so this change was doubling up and causing problems.
> Rolls back OGL Projection correction.

- Engine/source/gfx/gfxDrawUtil.cpp
- Engine/source/math/mPolyhedron.impl.h
Fixes the drawUtil rendering of polyhedrons by correcting the index ordering to work with triangleStrip as opposed to Fan.
> Fixes the drawUtil rendering of polyhedrons

- Engine/source/gfx/gl/gfxGLCardProfiler.cpp
- Engine/source/gfx/gl/gfxGLCircularVolatileBuffer.h
- Engine/source/gfx/gl/gfxGLDevice.cpp
- Engine/source/gfx/gl/gfxGLDevice.h
- Engine/source/gfx/gl/gfxGLShader.cpp
- Engine/source/gfx/gl/gfxGLStateBlock.cpp
- Engine/source/gfx/gl/gfxGLTextureManager.cpp
- Engine/source/gfx/gl/gfxGLTextureObject.cpp
- Engine/source/gfx/gl/gfxGLTextureTarget.cpp
- Engine/source/gfx/gl/gfxGLVertexBuffer.cpp
- Engine/source/gfx/gl/gfxGLVertexDecl.cpp
- Engine/source/gfx/gl/gfxGLWindowTarget.cpp
This caches OpenGL extensions that are not part of the core profile. It uses a struct of Boolean values to avoid function call overhead as @rextimmy suggestion. Extensions that run during initalization are not cached, as there really is no reason to as of now. It is fairly easy to add more extensions to the cache as needed. 
This PR also removes the old extensions that are no longer needed.
Finally, it replaces a call of glGenMipmapEXT to glGenMipmap, as we are in the core profile now!
> OpenGL Extension Caching

- Engine/source/T3D/physics/bullet/btPlayer.cpp
- Engine/source/T3D/physics/bullet/btPlayer.h
When using bullet physics, it ensures the player does not move when the world sim is paused, as well as correcting the surface check when walking to test against the max run angle.
> Fixes some bullet physics issues with the player class

- Engine/source/T3D/physics/physx3/px3Player.cpp
- Engine/source/T3D/physics/physx3/px3Player.h
The testSpacials() and setSpacials() functions have been added to test for overlaps before changing character poses and to update the character controller with the new dimensions.
> Spacial update for Px3 character controller

- Engine/source/navigation/navMesh.cpp
- Engine/source/scene/sceneObject.cpp
- Engine/source/scene/sceneObject.h
and adds a NavMeshIgnore method for object-instances to filter them out.
(primary usage this end: bots pathing around one another via a cyclic call to the previsouly turned over NavMeshUpdateAll/NavMeshUpdateAroundObject)
> allows navmeshes to generate for most scene objects, 

- Engine/source/T3D/physics/bullet/btBody.cpp
- Engine/source/T3D/physics/bullet/btBody.h
- Engine/source/T3D/physics/physicsBody.h
- Engine/source/T3D/physics/physx3/px3Body.cpp
- Engine/source/T3D/physics/physx3/px3Body.h
- Engine/source/T3D/physics/physx3/px3World.cpp
- Engine/source/T3D/physics/physx3/px3World.h
- Engine/source/T3D/vehicles/vehicle.cpp
- Engine/source/T3D/vehicles/vehicle.h
Makes vehicles create a basic physics body when using one of the physics plugins so that they can collide with other physics-enabled objects.
Based on @rextimmy 's work.
(Resubmitted due to git shenanigans)
> Makes vehicles work with the physics plugins.

- Engine/source/lighting/shadowMap/lightShadowMap.cpp
worst case scenario fallback for if we can't track down why vector lighting seems determined to shift positions periodically based upon some influence by the dynamicrefreshfrequency rate
> fallback - dynamic shadow cache nuking (static refresh delay preserved)

- Engine/lib/collada/src/dae/daeMetaGroup.cpp
- Engine/lib/convexDecomp/NvHashMap.h
A bool is not a pointer and a reference has to be returned.
> Fixed compile errors on linux (obvious programming faults).

- Engine/source/console/compiledEval.cpp
- Engine/source/core/stream/stream.cpp
Adds some pointer cleanup if we bail out of creating a new object for whatever reason, mostly pertainig to datablocks.
If we exit out and delete our object, we were had the possibility of currentNewObject pointing to a bad memory address, potentially causing a crash. The cleanup of the pointer on the delete by setting it to NULL prevents that.
> New object pointer cleanup

- Templates/Empty/game/shaders/common/lighting/advanced/gl/dbgColorBufferP.glsl
- Templates/Empty/game/shaders/common/lighting/advanced/gl/dbgSpecMapVisualizeP.glsl
- Templates/Full/game/shaders/common/lighting/advanced/gl/dbgColorBufferP.glsl
- Templates/Full/game/shaders/common/lighting/advanced/gl/dbgSpecMapVisualizeP.glsl
These debug viz shaders don't compile linux side. Should be postFX.glsl and not postFx.glsl but that include is not even needed for these anyway ;)
> Linux vix shader fixes

- Engine/source/gui/controls/guiBitmapBarCtrl.cpp
- Engine/source/gui/controls/guiBitmapBarCtrl.h
clipped bitmap. by default clips the right hand side based on (the percent entry/100).
options:
vertical clips the bottom
flipClip inverts direction (so vertical off would remove bits from the left, vertical on from the top)
> New: GuiBitmapBarCtrl

- Engine/source/T3D/physics/bullet/btBody.cpp
- Engine/source/T3D/physics/physx3/px3Body.cpp
Removes the body for the physicsBody's findContact function until it's ready to be corrected/used with the entity/component stuff.
This corrects an error for PhysX compilation due to unready code being inadvertently added in with the e/c update.
> Removes the body for the physicsBody's findContact

- Engine/source/T3D/aiPlayer.h
Removes an extraneous Namespace usage on a function declaration that could cause compiler errors.
> Removes an extraneous Namespace usage

- Engine/source/platform/types.gcc.h
- Engine/source/platformX86UNIX/x86UNIXMath.cpp
Flips the i386 preprocessor flag to use __i386__, which is apparently more standard.
> Flips the i386 flag to __i386__

- Engine/source/T3D/fx/precipitation.cpp
Properly initiates the max number of drops per batch to avoid possible corruption issues.
Pertains to #1680
> Precipitation maxVBDrops correction.

- Engine/source/math/mRotation.cpp
Changes back "Rotation =" values in mission files to the old "rotation =" since all other values are also lowercase.
> changes "Rotation" instead of "rotation" #1702

- Engine/source/shaderGen/GLSL/shaderFeatureGLSL.cpp
- Engine/source/shaderGen/HLSL/shaderFeatureHLSL.cpp
on the hlsl side: corrects improperly applied specularpower (slider in conjunction with cubemap). 
gl side kills a redundant test
> 3.9 fix: corrects improperly applied specularpower

- Tools/CMake/torque3d.cmake
Support for the new VS_STARTUP_PROJECT directory property. This was added in CMake 3.6
> CMake support for VS_STARTUP_PROJECT

- Engine/source/T3D/shapeBase.cpp
Fix to include a needed include for the accumulation volume stuffs
> Fix to include a needed include for the accumulation volume stuffs

- Engine/source/ts/tsRenderState.cpp
caused issues with https://github.com/GarageGames/Torque3D/pull/1711
> accutex was left out of the copy constructor for TSRenderState.

- Engine/source/ts/tsMesh.cpp
- Engine/source/ts/tsShape.cpp
- Engine/source/ts/tsShape.h
- Engine/source/ts/tsShapeConstruct.cpp
- Engine/source/ts/tsShapeConstruct.h
- Engine/source/ts/tsShapeEdit.cpp
- Engine/source/ts/tsShapeInstance.cpp
- Engine/source/ts/tsShapeInstance.h
Due to a few typos and bad edge cases, meshes which use the following wont load correctly with the HW skinning changes:
- Secondary UV coords
- Colors
- Parented meshes combined with removed meshes
- Loading meshes using a 64bit memory address
This PR fixes this problem.
> Fix load with DTS shapes introduced with HW skinning changes

- Engine/source/core/color.h
- Engine/source/lighting/advanced/advancedLightBinManager.cpp
*Note this will likely take a second pass once we kill Directx 9 and go all-in on using SGRB buffers
**All in may end up excluding Mac O/S. Getting mixed reports there.
> adds toLinear and toGamma helper functions for ColorF, uses the former in adjusting lights.

- Engine/source/gfx/D3D11/gfxD3D11Cubemap.cpp
> Correctly copy mipmap sub resources for DX11 cubemap.

- Engine/lib/nativeFileDialogs/nfd_win.cpp
Removes the unnecessary include of altbase in nativefiledialogs, which was causing problems with express versions of VS.
> Removes the unnecessary include of altbase in nativefiledialogs

- Engine/source/ts/tsShapeInstance.cpp
to preserve current widescreen vs 4:3 windows while closer matching prior release results
Long Term we'll likely want to circle back around to https://github.com/Azaezel/Torque3D/commit/10f528280e205b273457b6ae40d35ba3fc95ea39
> short term LOD correction

- Engine/source/navigation/navMesh.cpp
Write Links only when mLinkIDs.size() > 0
> Fix crash when saving NavMesh file without Links

- Engine/source/core/ogg/oggTheoraDecoder.cpp
- Engine/source/core/ogg/oggTheoraDecoder.h
Reverts changes to oggTheoraDecoder.cpp which prevent compiling and running on 64bit systems.
> Revert TORQUE_CPU_X64 changes to oggTheoraDecoder

- Engine/lib/libogg/include/ogg/.gitignore
Oops my bad, totally forgot to include this .gitignore with the original PR for this
> .gitignore to exclude cmake generated config_types for libogg

- Engine/source/terrain/glsl/terrFeatureGLSL.cpp
- Engine/source/terrain/hlsl/terrFeatureHLSL.cpp
- Engine/source/terrain/terrCellMaterial.cpp
for terrains to support multi-pass blending. 
Do note this will only address https://github.com/GarageGames/Torque3D/issues/1701 . Comprable blending artifacts for normals on objects with multiple layers with the normal maps on layer 0 and subsequent layers lacking a normal will need to be addressed separately.
> embeds blendtotal into the low bit for the normal|depth buffer 

- Engine/source/core/util/swizzle.h
In this case, memcpy is redundant as the data is copied according to the copy loop in the next block.
> Fix redundant memcpy in swizzle ToBuffer method

- Engine/source/collision/abstractPolyList.cpp
Hi all,
This is a minefield, which is a class inherited from Trigger. 
Ok, and because Military intelligence should work, enemies (Tanks) must avoid go across it, because it's his own minefield! Then I added the minefield to NavMesh. Then I realized that I had to add a buildPolyList function to my class, which uses AbstractPolyList::addBox().
And as you can see, the edges of  the box is not completely etched from the NavMesh.
Looking at AbstractPolyList::addBox() I saw that only add one triangle per face, so I fix it and that the result:
With this PR it's added the second triangle to the face, but I can't say If this was originally made by design, or if breaks something else...
> Fixes AbstractPolyList::addBox(). Complete each face with missing 2nd triangle.

- Engine/source/core/dataChunker.cpp
- Engine/source/core/dataChunker.h
This reduces the amount of memory allocations DataChunker uses.
In addition this also fixes a bug where "next" was not cleared when blocks were free'd.
> Reduce the amount of blocks of memory DataChunker uses

- Engine/source/windowManager/sdl/sdlWindow.cpp
Makes sure the key modifiers are passed along with mouse move and wheel inputs when using SDL.
> Makes sure the key modifiers are passed along with mouse actions.

- Engine/source/T3D/gameBase/moveManager.h
- Engine/source/T3D/objectTypes.h
- Engine/source/console/consoleObject.h
- Engine/source/console/sim.h
- Engine/source/core/stream/fileStream.h
- Engine/source/gfx/sim/debugDraw.h
- Engine/source/gui/controls/guiTextListCtrl.h
- Engine/source/math/mBoxBase.h
- Engine/source/math/util/frustum.h
- Engine/source/platform/platformMemory.cpp
- Engine/source/scene/simPath.h
- Engine/source/scene/zones/sceneZoneSpaceManager.h
- Engine/source/sfx/sfxSoundscape.h
- Engine/source/sim/netStringTable.h
- Engine/source/terrain/terrRender.h
Tweaks any enums that use uint_max values so that they have hard types to avoid any compiler kerfluffles with C++11 value narrowing, specifically pertaining to clang.
> Force enums using unsigned values to actually hard type to U32

- Engine/source/math/mBoxBase.h
assertfatal doesn't do anything in release builds, so also added a failure enum.
> clang catch: boxBase's getPlanePointIndex method wasn't returning values in all cases.

- Engine/source/gui/controls/guiTreeViewCtrl.cpp
- Engine/source/gui/worldEditor/worldEditor.cpp
Fixes Prefab creation handling of SceneObjects and SimGroups.
Fixes SceneObjects where the default icon incorrectly defaulted to the simgroup folder rather than the generic class object when the class has no specific class icon.
> Fixes up some erroneous behavior with Simgroup parentage.

- Engine/source/gui/editor/guiInspector.cpp
Renames the engine method arg to avoid name confusion.
> GuiInspector's findByObject method fix.

- Templates/Empty/game/tools/worldEditor/scripts/editors/creator.ed.cs
- Templates/Full/game/tools/worldEditor/scripts/editors/creator.ed.cs
Fixes minor issue where if a prefab was in one of the root directories rather than further in the heirarchy, it would incorrectly add a folder of the prefab's name that contains the prefab in the creator menu's prefabs tab.
> Fixes prefabs in root dirs having extra folders in creator.

- Engine/source/T3D/lightBase.cpp
- Engine/source/T3D/lightDescription.cpp
- Engine/source/environment/scatterSky.cpp
- Engine/source/environment/sun.cpp
Hides the light's dynamic refresh rate field to avoid confusion, leaving only the static refresh rate field to be edited in reference to #1707
> Hides the light's dynamic refresh rate field in the editor

- Templates/Empty/game/tools/gui/guiPlatformGenericMenubar.ed.cs
- Templates/Full/game/tools/gui/guiPlatformGenericMenubar.ed.cs
Sanity check for if the GuiPlatformGenericMenuBar class is valid before trying to load a menubar that uses it, in the event that SDL isn't enabled, or other similar circumstances.
Corrects issue #1745.
> Sanity check for if the GuiPlatformGenericMenuBar class

- Tools/CMake/modules/module_testing.cmake
(test for #if +uninitialized #defines)
leaving that as an option, but off by default to allow filtering through engine specific #defines for issues, rather than wading through the spam kicked up by the plugin.
> clang: The unit test suite doesn't play nice with -wundef

- Engine/source/navigation/navMesh.cpp
It's not working because on onNavMeshUpdate the string comparation will never succeed, and will never call  call navpath::plan()
```
DefineEngineMethod(NavPath, onNavMeshUpdate, void, (const char *data),,
"@brief Callback when this path's NavMesh is loaded or rebuilt.")
{
if(object->mMesh && !dStrcmp(data, object->mMesh->getIdString()))
object->plan();
}
```
> Fix  for NavPath is not updated when navMesh has change. 

- Engine/source/terrain/terrCellMaterial.cpp
- Engine/source/terrain/terrCellMaterial.h
This just re-enables face culling for the terrain that was disabled when deferred shading replaced deferred lighting.
> re-enable face culling for the terrain

- Engine/source/gui/editor/guiInspectorTypes.cpp
Fills out the automaticly filled inspector entries for AbstractClassRep::FieldFlags::FIELD_ComponentInspectors with a pressable button.
> FIELD_ComponentInspectors inspector hook up

- Engine/source/scene/simPath.cpp
as well as enlarges both the look and 'physical' handle size for ease of use.
> directional coloration for pathnodes,

- Engine/source/app/game.cpp
- Engine/source/app/mainLoop.cpp
- Engine/source/app/net/serverQuery.cpp
- Engine/source/app/net/tcpObject.cpp
- Engine/source/console/telnetConsole.cpp
- Engine/source/console/telnetDebugger.cpp
- Engine/source/core/stream/stream.cpp
- Engine/source/core/stream/stream.h
- Engine/source/platform/platformNet.cpp
- Engine/source/platform/platformNet.h
- Engine/source/platform/platformNetAsync.cpp
- Engine/source/platform/platformNetAsync.h
- Engine/source/platform/test/netTest.cpp
- Engine/source/sim/netConnection.cpp
- Engine/source/sim/netInterface.cpp
- Engine/source/sim/netInterface.h
- Templates/Empty/buildFiles/config/torque3D_dedicated.conf
- Templates/Full/buildFiles/config/torque3D_dedicated.conf
- Templates/Full/source/torqueConfig.h
- Tools/CMake/torque3d.cmake
- Tools/projectGenerator/classes/NPWebPlugin.php
- Tools/projectGenerator/classes/Torque3D.php
- Tools/projectGenerator/libs/Torque3D.conf
Implements preliminary IPV6 support. 
What works:
- Connecting to ipv4 addresses (yes, this is backwards compatible)
- Connecting to ipv6 addresses
- Browsing for ipv6 servers on a LAN
- Working with ipv6 TCP sockets
- Returning IPV6 addresses from the master server
- Registering an IPV6 server with the master server
IPv6 addresses may be represented by the following formats:
- `IP6:address`
- `IP6:[address]:port`
- `IP^:[address]:port%interface`
_NOTE_: ipv6 by default is disabled. You need to set `$pref::Net::IPV6Enabled` to 1 in order for a server to listen on ipv6 and also to be able to query ipv6 servers.
For a suitable master server to test with, check out https://github.com/jamesu/PushButton-Master-Server/tree/ipv6_support
For LAN testing, any ipv6 network should work - just make …
> Preliminary IPV6 Support

- Engine/source/lighting/shadowMap/lightShadowMap.cpp
- Engine/source/lighting/shadowMap/lightShadowMap.h
- Engine/source/lighting/shadowMap/shadowMapManager.cpp
- Engine/source/lighting/shadowMap/shadowMapPass.cpp
- Engine/source/lighting/shadowMap/shadowMapPass.h
adds a $pref::Shadows::teleportDis and $pref::Shadows::turnRate (defaults 4, and 1 respectively)
if either is exceeded during a given frame, shadow chaches are forced to refresh themselves.
> motion based updates for shadow caching

- Engine/source/shaderGen/GLSL/bumpGLSL.cpp
- Engine/source/shaderGen/GLSL/shaderFeatureGLSL.cpp
- Engine/source/shaderGen/HLSL/bumpHLSL.cpp
- Engine/source/shaderGen/HLSL/shaderFeatureHLSL.cpp
removed that, as well as a prior attempted workaround.
> factoring in tangentW causes parallax to swap specular highlight directions. 

- Tools/CMake/basics.cmake
Turns out Visual Studio 2015 is doing some aggressive optimizations that where not present in older versions of Visual Studio. Using fp:fast is causing slight floating point inaccuracies that eventually filter down and we end up getting rotations that are wrong and causing havoc when saving mission files. Changed the setting back to the default fp:precise
> Change VS to use the default fp:precise

- Engine/source/shaderGen/GLSL/shaderFeatureGLSL.cpp
- Engine/source/shaderGen/HLSL/shaderFeatureHLSL.cpp
went overzealous on the bitangent cleanup when reviewing parallax. the W multiplier can and should stay. the y flip can remain gone.
> uts bitangent direction determinant back

- Engine/source/T3D/prefab.cpp
- Engine/source/T3D/prefab.h
- Engine/source/T3D/tsStatic.h
- Engine/source/gui/worldEditor/worldEditor.cpp
- Engine/source/gui/worldEditor/worldEditor.h
- Engine/source/shaderGen/GLSL/shaderFeatureGLSL.cpp
- Engine/source/shaderGen/HLSL/shaderFeatureHLSL.cpp
- Templates/Empty/game/tools/worldEditor/scripts/menuHandlers.ed.cs
- Templates/Empty/game/tools/worldEditor/scripts/menus.ed.cs
- Templates/Full/game/tools/worldEditor/scripts/menuHandlers.ed.cs
- Templates/Full/game/tools/worldEditor/scripts/menus.ed.cs
Makes it so prefabs can correctly 'export to collada' by running the buildPolyList function on it's children.
Also adds a 'Bake Selection to Mesh' option to the tools menu in the editor to export the selected mesh to a collada file, and then replaces the selection with a TSStatic.
> Adds some bake-to-collada functions

- Engine/source/windowManager/sdl/sdlWindow.cpp
- Engine/source/windowManager/sdl/sdlWindowMgr.cpp
- Engine/source/windowManager/sdl/sdlWindowMgr.h
- Engine/source/windowManager/windowInputGenerator.cpp
- Engine/source/windowManager/windowInputGenerator.h
Fixes a bug with SDL where the ~ would be applied to the console text entry responder. could apply to other first responders as well.
> fix SDL text events from generating a ~ key when opening the console

- Engine/source/gfx/gl/gfxGLTextureManager.cpp
> GL::Workaround::noCompressedNPoTTextures profile is no longer used

- Engine/source/gfx/D3D11/gfxD3D11Device.cpp
- Engine/source/gfx/D3D11/gfxD3D11Device.h
- Engine/source/gfx/D3D11/gfxD3D11Target.cpp
- Engine/source/gfx/D3D11/gfxD3D11Target.h
- Engine/source/gfx/gl/gfxGLWindowTarget.cpp
- Engine/source/gfx/gl/gfxGLWindowTarget.h
- Engine/source/gfx/gl/sdl/gfxGLDevice.sdl.cpp
- Engine/source/gfx/gl/win32/gfxGLDevice.win.cpp
Add support for multiple canvas for GL & DX11. Do note there is a problem with SDL and multiple windows but that is a separate case. All 3 gfx work perfectly with win32 platform code.
> Multiple canvas support for GL and DX11

- Engine/source/gfx/D3D11/gfxD3D11Device.cpp
- Engine/source/gfx/D3D11/gfxD3D11Device.h
- Engine/source/gfx/D3D11/gfxD3D11Shader.cpp
- Engine/source/gfx/D3D11/gfxD3D11Shader.h
- Engine/source/gfx/D3D11/gfxD3D11StateBlock.cpp
- Engine/source/gfx/D3D11/gfxD3D11StateBlock.h
Various updates i been meaning to chuck in for ages:
* Caching sampler states
* Better tracking of sampler ranges in use for binding time
* Feature level 10 & 10.1 support
* Full-screen fix where window has no focus on startup
* Don't add DX11 adapters to the adapter list when they are not supported by the system (causes a crash when selected)
* D3DPER debug events
> DX11 updates

- Engine/source/gfx/D3D11/gfxD3D11CardProfiler.cpp
- Engine/source/gfx/D3D11/gfxD3D11CardProfiler.h
- Engine/source/gfx/D3D11/gfxD3D11Device.cpp
- Engine/source/gfx/D3D11/gfxD3D11Device.h
- Engine/source/gfx/D3D11/gfxD3D11Shader.cpp
*Fixes up a problem where shader model version was not getting set for shader macros.
*Adds feature level string to the version string of the card profiler.
> D3D11 shadermodel version fix

- Engine/source/gui/core/guiOffscreenCanvas.cpp
- Engine/source/gui/core/guiOffscreenCanvas.h
Related to: http://forums.torque3d.org/viewtopic.php?f=10&p=6964#p6964
These small changes fix the rendering in the named texture of a guiOffscreenCanvas with 3d views.
Without this change, the objects in the 3d view are copied as they're created and that causes depth issues (objects behind being rendered in front).
Creating the gui with the field "useDepth" as true enables the fix.
It's off by default so guiOffscreenCanvas that don't use 3d views or don't need the texture part won't get the extra workload of the fix.
-Example of its use-
Add these functions to a .cs script in a "Full" project and exec it:
`                                                  
//createRearView(0);
//createRearView(1);
function createRearView(%depthtest)
{
if(!isObject(RearViewUpdater))
{
%tickObj = new …
> Adding depth option to the texture of guiOffscreenCanvas

- Engine/source/T3D/physics/bullet/btWorld.cpp
- Engine/source/T3D/physics/physicsWorld.cpp
- Engine/source/T3D/physics/physicsWorld.h
- Engine/source/T3D/physics/physx3/px3World.cpp
- Engine/source/T3D/physics/physx3/px3World.h
Allows tuning of the physics substeps and step time. Bullet before was using the default of 1 substep. Potentially these would be good values to have in the levelInfo so they can be tuned on a per level basis depending on the physics needs of that level.
Thanks @JeffProgrammer for pointing out the bullet side, never noticed it before.
> Physics timing

- Engine/source/T3D/vehicles/guiSpeedometer.cpp
This patch fixes several bugs in guiSpeedometerHud::onRender():
-Caused hard crash due to unmatched pushWorldMatrix() call.
-Routine did not rotate/translate the control, causing render to fail in all cases.
-Control would not render for player-mounted vehicles (i.e. when used in a fps context) .
> Gui speedometer hud

- Engine/source/gfx/bitmap/gBitmap.cpp
- Engine/source/gfx/gfxTextureManager.cpp
- Engine/source/math/mMathFn.h
Fixtures a problem where textures created with GBitmap class that are non square (i.e like 1024x512) have an incorrect mipmap level calculated.
> Texture crash

- Templates/Empty/game/core/scripts/client/screenshot.cs
- Templates/Empty/game/scripts/client/default.bind.cs
- Templates/Full/game/core/scripts/client/screenshot.cs
- Templates/Full/game/scripts/client/default.bind.cs
EDIT: sry I forgot to add a description..... this add a better function of the video recording and add a shortcut.
> enable video recording

- Engine/source/gfx/video/videoCapture.cpp
Adds a check to the record movie call so that it only happens in Release mode, to avoid crash issues with theora and debug mode. Related to notes on #1894
> Adds a check to the record movie call

- Engine/source/platform/platformNet.h
Hotfix to re-add the prior static function fix for these functions that was accidentally removed.
> Hotfix to re-add the prior static function fix in platformNet

- Engine/source/T3D/fx/lightning.cpp
This PR fix the warningFlashes() method, that doesn't randomly select the spot to strike, all the lightning bolts will always strike in the same place.
EDIT: typo :D
> fix warningFlashes() of lightning class

- Engine/source/forest/editor/forestSelectionTool.cpp
- Templates/Empty/game/tools/forestEditor/forestEditorGui.gui
- Templates/Full/game/tools/forestEditor/forestEditorGui.gui
Fixes a crash when you try to delete things without being in selection mode in the forest editor. Adds a sanity check that everything is properly set up before attempting the delete action.
Also adds a fix to the mesh item tab in the forest editor to correct odd selection behavior that could erroneously cause selection of two items in the list when you only clicked one.
In reference to #1936
> Fixes some issues with forest editor.

- Engine/source/T3D/fx/lightning.cpp
- Engine/source/T3D/fx/lightning.h
added new feature strikeObject to lightning.
Now you can throw a lightning to objects  derived from shapebase, like players, Items, AI, etc.
EDIT: typo
> added strikeObject lightning feature

- Engine/source/windowManager/sdl/sdlSplashScreen.cpp
Does better sanity checking on cleanup for the splash screen closing with SDL. Could erroneously get called a second time and if we'd already cleared the images and textures, it could crash.
This fixes that.
> Does better sanity checking on cleanup for the splash screen closing in SDL

- Engine/source/math/mConsoleFunctions.cpp
- Engine/source/math/mathUtils.cpp
- Engine/source/math/mathUtils.h
Adds the getSignedAngleBetweenVectors function, which is like the existing getAngleBetweenVectors, but will returned a signed angle value, which helps to inform the full 360 angle, rather than the 'nearest 180'.
> Adds the getSignedAngleBetweenVectors function

- Engine/source/platform/platformNet.cpp
[BugFixanalysisforissue1951.docx](https://github.com/GarageGames/Torque3D/files/914377/BugFixanalysisforissue1951.docx)
When two instances of Torque3D are running on the same network, one as a
hosted server and the other as a client, the client is unable to connect
to the server. The program now can open a socket. This was obviously a
typo. To find the error I just searched for keywords containing socket,
open, open socket, and opensocket till I found the correct file. The
other error was in how the program processed “non fatal” errors. I just
outputed the error to the main console and devised that the socket
should not be closed for a WSAEWOULDBLOCK error 10035 "It is normal for
WSAEWOULDBLOCK to be reported as the result from calling connect on a
nonblocking SOCK_STREAM socket, since …
> Possible fix to issue #1951

- Engine/source/gfx/bitmap/gBitmap.cpp
- Engine/source/gfx/bitmap/gBitmap.h
- Engine/source/gfx/bitmap/loaders/bitmapBmp.cpp
- Engine/source/gfx/bitmap/loaders/bitmapGif.cpp
- Engine/source/gfx/bitmap/loaders/bitmapJpeg.cpp
- Engine/source/gfx/bitmap/loaders/bitmapMng.cpp
- Engine/source/gfx/bitmap/loaders/bitmapPng.cpp
- Engine/source/gfx/bitmap/loaders/bitmapTga.cpp
*note, DDS bypasses the gbitmap method chain in question.
> adds profiling to the various gbitmap loaders*

- Engine/source/T3D/turret/aiTurretShape.cpp
- Engine/source/T3D/turret/aiTurretShape.h
Implements feature(s) requested in issue #1272 
The first feature is exposing a function to Torquescript that allows retrieving the count of the total number of objects on a turret's ai ignore list, ignoreListCount().
The second feature is exposing a function to Torquescript that allows retrieving a reference to an object on an AI turret's ignore list based off of the index in the list of that object, rather than the object's ID (so the object's ID does not have to be known beforehand).  The feature request issue #1272 requests for this feature to return the object's ID but then shows an example modifying the object directly (increasing the health of the object by 10), so to fulfill the requested functionality based on the example, this feature returns a reference to the object itself so …
> Ai turret ignore list functions

- Engine/source/core/util/str.cpp
Fixes #1738 without redundant checks. Because of the while loop on line 1616 giving the variable p its value, the check against base is redundant.
> Better bug fix for #1738 (str.cpp)

- Templates/Full/game/art/datablocks/weapons/grenadefx.cs
- Templates/Full/game/art/datablocks/weapons/rocketfx.cs
- Templates/Modules/FPSGameplay/scripts/datablocks/weapons/grenadefx.cs
- Templates/Modules/FPSGameplay/scripts/datablocks/weapons/rocketfx.cs
This addresses issue #1501 
The property variable "dragCoefficient" was misspelled in various datablocks in the grenadeFX.cs and rocketFX.cs files, both in the Templates directory locations and the Modules directory locations.  It was misspelled as "dragCoeffiecient", as noted in the issue ticket.  Some but not all of those locations were spelled correct, but the property was misspelled in numerous other locations in those two files as well.  This corrects the spelling of those properties so that users trying to reference those properties in other parts of the Torquescript will be able to reference them by the correct name.  
For instance, if one had a list of datablocks that included some where the property was spelled correctly and some where it was spelled incorrectly, and wanted to …
> Drag coefficient misspelled

- Templates/Full/game/art/decals/managedDecalData.cs
Renamed the screenStartRadius and screenEndRadius properties in the bulletHoleDecal datablock and ScorchRXDecal datablock to fadeStartPixelSize and fadeEndPixelSize properties, respectively, to match names of the properties as defined in the decalData.cpp file, as noted in issue #1498
Among other possible fixes, this makes the size of the bullet hole decal's actually random in size now, instead of always being the exact same size.
> Fixed old names of decal properties

- Engine/source/console/consoleFunctions.cpp
- Engine/source/core/strings/unicode.cpp
- Engine/source/core/util/tSignal.h
- Engine/source/forest/forestCollision.h
- Engine/source/sfx/media/sfxVorbisStream.cpp
Hello,
I have found and fixed some bugs using PVS-Studio tool. PVS-Studio is a static code analyzer for C, C++ and C#: https://www.viva64.com/en/pvs-studio/
Analyzer warnings:
* [V591](https://www.viva64.com/en/w/V591/) Non-void function should return a value. [Engine/source/core/util/tSignal.h 165](https://github.com/GarageGames/Torque3D/blob/development/Engine/source/core/util/tSignal.h#L165)
_Comment_: If there is needed to prevent the copying of the object, then there is no need to provide the definition of the copy constructor and the assignment operator, because the member functions and `friend` functions can still call them. 
_Note_: If the code is compiled by a compiler with support for the C++11 standard, you can delete them using the keyword `delete` like this:
<pre><code>.... …
> Checking Torque3D with PVS-Studio static analyzer

- Engine/source/gfx/gfxDrawUtil.cpp
This PR fixes a bug that was causing GFXDrawUtil::drawTextN() to draw one character more than requested if in_string is longer than n. This bug shows up in the GuiMessageVectorCtrl when lines are split. The first character of the second part of the string is duplicated on the line above. You can trace through from here: https://github.com/GarageGames/Torque3D/blob/development/Engine/source/gui/game/guiMessageVectorCtrl.cpp#L717 to see it happen, if you have a control with split lines.
Specifically,
GFX->getDrawUtil()->drawTextN(mProfile->mFont, start, "0123456789", 5, mProfile->mFontColors, mMaxColorIndex, 0.0f);
will render 6 characters instead of 5 as requested.
> BugFix for GFXDrawUtil::drawTextN()

- Engine/source/environment/VolumetricFog.cpp
Fixes a memory leak on clients and prevents a crash from deleting a RTT target while it's still registered with the GFX device.
> VolumetricFog memory leak fix

- Engine/source/console/consoleDoc.cpp
Console Classes dump fix. It was running aground on having a case where there was a empty string value for the 'usage' field in the class header. This would break the allocation because we're allocating nothing. This rejects it if the usage field is an empty string.
This is in reference to issue #2005.
> Console Classes dump allocation fix

- Engine/source/console/engineFunctions.h
ps the #pragma pack call from 4 to 8 when using 64bit, as per suggested settings. This shaves off a lot of compatibility warnings.
> Ups the #pragma pack call from 4 to 8 when using 64bit

- Engine/source/console/engineFunctions.h
Works around the regressive behavior in the VSC++ compiler for VS2017 where the variadic templates would not compile correctly. Issue should be patched in future versions, so for now it'll target the 1910 version specifically.
> VS2017 compiler workaround

- Templates/Full/game/shaders/common/gl/hlslCompat.glsl
Removes a completely pointless macro that Intel GL drivers don't like.
> Intel GL Fix

- Engine/source/console/engineFunctions.h
Fixes the #if rather than using the #ifdef.
> #if cleanup for the VS2017 workaround

- Engine/source/T3D/physics/physicsShape.cpp
Fixes collision shape assignment after a PhysicsShapeData resource change signal is triggered.
> PhysicsShapeData collision fix

- Engine/source/console/console.cpp
- Engine/source/console/console.h
- Engine/source/forest/glsl/windDeformationGLSL.cpp
- Engine/source/forest/hlsl/windDeformationHLSL.cpp
- Engine/source/gfx/D3D11/gfxD3D11Device.cpp
- Engine/source/gfx/gl/gfxGLDevice.cpp
- Engine/source/shaderGen/GLSL/bumpGLSL.cpp
- Engine/source/shaderGen/GLSL/pixSpecularGLSL.cpp
- Engine/source/shaderGen/GLSL/shaderFeatureGLSL.cpp
- Engine/source/shaderGen/GLSL/shaderGenGLSL.cpp
- Engine/source/shaderGen/HLSL/bumpHLSL.cpp
- Engine/source/shaderGen/HLSL/pixSpecularHLSL.cpp
- Engine/source/shaderGen/HLSL/shaderFeatureHLSL.cpp
- Engine/source/shaderGen/shaderGen.cpp
- Engine/source/shaderGen/shaderGen.h
- Engine/source/terrain/glsl/terrFeatureGLSL.cpp
- Engine/source/terrain/hlsl/terrFeatureHLSL.cpp
Reworks the $Core::commonShaderPath variable usage to be a static variable in ShaderGen for efficiency(only one getVariable when shadergen is initialized), as well as implements the ability to set a default value, and ensures that it tries to set a path even if the pref variable is missing which is important for ported projects from older builds.
> Reworks the $Core::commonShaderPath variable usage

- Engine/source/gfx/D3D11/gfxD3D11Device.cpp
- Engine/source/gfx/D3D11/gfxD3D11Device.h
This fixes a potential crash with D3D11 that usually happens when playing a video or displaying a splash screen and resizing the window
> Fix potential crash with D3D11

- Engine/source/console/engineFunctions.h
Unfortunately Microsoft have told us big fat lies and that the template bug would be fixed with update 15.3(msc_ver 1911)but it hasn't been fixed. This leaves us with little choice for now but to do a _MSC_VER >= 1910 until this problem is resolved and we know exactly what versions numbers we are dealing with.
> Support for VS 15.3 update

- Engine/source/console/consoleTypes.h
Hotfix to make VS2017 15.3 play nice. Offsetof behavior - specifically builtin - is unreliable in release(and broken in debug), so explicitly defining it to use a reliable method for now.
> Hotfix to make VS2017 15.3 play nice.

- Engine/source/gfx/gfxTextureManager.cpp
from@rextimmy: reports the same texture used with 2 conflicting textureProfiles (flipping back and forth causes duplicates)
> textureProfile conflict reporting

- Engine/source/shaderGen/shaderGen.cpp
Moves the initialization of the shader common path const var so it is set before we do an initial setup of some shadergen fields.
Resolves #2079
> Fixes smCommonShaderPath init order

- Engine/source/gui/worldEditor/gizmo.cpp
- Templates/Full/game/tools/worldEditor/scripts/editorPrefs.ed.cs
Sets the default grid snap size to 1 rather than 10. 1 Seems like a more neutral default value, and also makes it match the displayed '1' in the UI interface as the default as well.
> Sets the default grid snap size to 1 rather than 10.

- Engine/source/gfx/gfxStringEnumTranslate.cpp
This commit eliminates 5 warnings output from VALIDATE_LOOKUPTABLE here: https://github.com/GarageGames/Torque3D/blob/development/Engine/source/gfx/gfxStringEnumTranslate.cpp#L167
And prevents a fatal error here: https://github.com/GarageGames/Torque3D/blob/development/Engine/source/gfx/gfxTextureManager.cpp#L1371
that occurs when called from GuiOffscreenCanvas::_setupTargets() for an OpenVROverlay because GFXFormatR8G8B8A8_LINEAR_FORCE  is used.
> Adds missing GFX Texture format strings

- Engine/source/console/consoleObject.h
- Engine/source/gui/editor/guiInspector.h
- Engine/source/gui/editor/guiInspectorTypes.cpp
- Engine/source/gui/editor/inspector/field.cpp
- Engine/source/gui/editor/inspector/field.h
- Engine/source/gui/editor/inspector/variableField.cpp
- Engine/source/gui/editor/inspector/variableField.h
- Engine/source/gui/editor/inspector/variableGroup.cpp
- Engine/source/gui/editor/inspector/variableGroup.h
- Engine/source/gui/editor/inspector/variableInspector.cpp
- Engine/source/gui/editor/inspector/variableInspector.h
Updates the VariableInspector, VariableGroup and VariableField objects to actually be useful. In addition to the original functionality of being able to have a var name passed in and search for all vars with that in it, it also lets you build out a completely custom Inspector.
Unlike the regular Inspector, which requires a specific object or objects, from which the fields are pulled from, this lets you manually create fields, which can tie into any given object and their fields, global vars, and also not only supports the engine types for fields, but also triggers a callback to script if a field type is not found allowing fully custom fields to be handled as needed.
> Updates the VariableInspector, VariableGroup and VariableField objects

- Engine/source/platform/platformNet.cpp
There was a small typo in `platformNet.cpp` where the `outBytesWritten` was being checked as a pointer, rather than a value, leading to the code not compiling under the latest xcode, but also this would've potentially allowed negative `outBytesWritten` values since the value being checked was a pointer, rather than the value of the pointer.
> Fixed a typo where the value of outBytesWritten was being clamped incorrectly.

- Templates/BaseGame/game/tools/forestEditor/forestEditorGui.cs
- Templates/BaseGame/game/tools/forestEditor/main.cs
- Templates/Full/game/tools/forestEditor/forestEditorGui.cs
- Templates/Full/game/tools/forestEditor/main.cs
Caused by space after objectID returned by parseMissionGroupForIds().  The meant that `isObject(%forestObject)` was returning false.
> Fix forest editor failing to load forest

- Engine/source/gui/worldEditor/terrainEditor.cpp
This edit makes it easy to enable/disable the terrain autopaint undo.
When using large terrains 1024+ the undo code takes an absolute age to complete, while the undo functionality can be disabled, it is spread throughout the code.
> #define AUTOPAINT_UNDO 

- Engine/source/gui/editor/guiInspector.cpp
- Engine/source/gui/editor/guiInspector.h
- Engine/source/gui/editor/inspector/componentGroup.cpp
- Engine/source/gui/editor/inspector/componentGroup.h
- Engine/source/gui/worldEditor/worldEditorSelection.cpp
- Templates/BaseGame/game/core/main.cs
- Templates/BaseGame/game/data/clientServer/scripts/server/connectionToClient.cs
- Templates/BaseGame/game/data/clientServer/scripts/server/levelDownload.cs
- Templates/BaseGame/game/tools/componentEditor/scripts/componentEditor.ed.cs
- Templates/BaseGame/game/tools/worldEditor/scripts/EditorGui.ed.cs
Fixes the inspector/component editor to display the components attached to an entity correctly in the inspector. Missed these bits of code with some of the prior e/c-related PR's.
> Fixes the inspector/component editor to display components

- Engine/source/console/consoleDoc.cpp
- Engine/source/console/consoleInternal.cpp
This will add better type information, the sizes of fixed-size arrays and indicate variadic parameters with 3 dots, when dumping the console documentation.
> Improve console dump with additional information

- Engine/source/gui/editor/guiShapeEdPreview.cpp
Hides the display of the 'camera axis' gizmo in the shape editor, as well as fixing it so that when you select a animation-only shapefile, it will correctly compute the shape bounds and thus render the bones correctly.
> Fix a few rendering issues in the Shape Editor

- Tools/CMake/torque3d.cmake
Fix for #2164 
Dependency was added by PR #1566. No longer needed now that DX SDK has
been replaced.
> Remove legacy_stdio_definitions.lib

- Engine/source/console/codeBlock.cpp
Fix from Torque2D for 64bit string table entries.
> Fix Torque3D 64bit DSOs.

- Engine/source/gui/core/guiCanvas.cpp
- Engine/source/gui/core/guiCanvas.h
- Engine/source/gui/editor/guiMenuBar.cpp
Stabilizes the add/remove behavior of menubars by also tracking the modeless background control the menubars use for proper cleanup as well.
Also fixes an issue where the findMenu call wasn't properly translating the incoming string to StringTableEntry.
> Fixes up some menubar issues.

- Templates/BaseGame/game/tools/worldEditor/scripts/editorPrefs.ed.cs
- Templates/BaseGame/game/tools/worldEditor/scripts/editors/creator.ed.cs
- Templates/Full/game/tools/worldEditor/scripts/EditorGui.ed.cs
- Templates/Full/game/tools/worldEditor/scripts/editorPrefs.ed.cs
- Templates/Full/game/tools/worldEditor/scripts/editors/creator.ed.cs
Removes the GameObject  folder insert for the scripted object creator grid, which was causing a UI screwup making the scripted objects overlap and jumble up.
Also reorgs the popup controls to match what's in the BaseGame template's setup, which should fix editor popups.
> Removes the GameObject folder insert for the scripted object creator grid

- Engine/source/console/typeValidators.h
example usage
FRangeValidator gravCoefFValidator(-10.f, 10.f);
addFieldV( "gravityCoefficient", TYPEID< F32 >(), Offset(gravityCoefficient, ParticleData), &gravCoefFValidator,
"Strength of gravity on the particles." ); <- clamps gravity within a -10 to 10 range when evaluating scriptt-set changes
mClamp(gravityCoefficient,gravCoefFValidator.getMin(),gravCoefFValidator.getMax()) for any calculations done on the source side would do the same at the point that is called, with a singularl lookup spot for the range.
> exposes getters for typevalidators.

- Tools/CMake/torque3d.cmake
Makes it so the SDL directory files aren't copied during a template file install.
> Makes it so the SDL directory files aren't copied during a template install.

- Engine/source/T3D/decal/decalDataFile.cpp
- Engine/source/T3D/fx/windEmitter.cpp
- Engine/source/collision/clippedPolyList.cpp
- Engine/source/console/simObjectList.cpp
- Engine/source/console/simSet.h
- Engine/source/core/tAlgorithm.h
- Engine/source/forest/forestDataFile.cpp
- Engine/source/forest/forestWindMgr.cpp
- Engine/source/gui/editor/guiEditCtrl.cpp
- Engine/source/materials/processedMaterial.cpp
- Engine/source/math/mIntersector.h
- Engine/source/math/mPlaneSet.h
- Engine/source/math/mathUtils.cpp
- Engine/source/postFx/postEffectManager.cpp
- Engine/source/scene/sceneContainer.cpp
- Engine/source/sfx/sfxController.cpp
- Engine/source/sfx/sfxDevice.cpp
- Engine/source/sfx/sfxSystem.cpp
- Engine/source/terrain/terrCellMaterial.cpp
- Engine/source/ts/tsLastDetail.cpp
tAlgorythm fed namespace T3D for better library interoperability. resulted in the need to specify usage in... a few places. (short version: it was blowing up being able to incorporate bits of std::*)
> changes find, swap, for_each, and delete_pointer from global to t3d namespace

- Engine/source/console/codeInterpreter.cpp
Remove unused variables and cleanup precision warnings as dSprintf takes a U32 for the size of the buffer to use.
Honestly though, dSprintf should probably use dsize_t. But that's a bigger change down the road.
> Small Cleanup to CodeInterpreter

- Engine/source/console/codeBlock.cpp
- Engine/source/console/consoleDoc.cpp
Both have small errors that cause crashing:
* `dumpConsoleClasses` has an off-by-1 error with a string buffer in `printClassHeader`
* `dumpConsoleFunctions` uses the wrong offset into the function code in `CodeBlock::getFunctionArgs`
> Fix dumpConsoleClasses / dumpConsoleFunctions

- Engine/source/console/consoleTypes.h
Remove a now-unneeded fix for offsetof on new versions of Visual Studio.
> Remove a now-unneeded fix for offsetof on new versions of Visual Studio.

- Engine/source/T3D/player.cpp
- Engine/source/T3D/shapeBase.cpp
- Engine/source/T3D/tsStatic.cpp
- Engine/source/ts/tsShapeInstance.cpp
- Engine/source/ts/tsShapeInstance.h
allows arbitrary material name string replacement, rather than forcing folks to start with base. ie: an entry of skin = "blue; area=fire";  would replace base_area_grid with blue_fire_grid as the used material
> allows for arbitrary reskinning

- Engine/source/T3D/turret/aiTurretShape.cpp
lets folks skip out on adding either and just using pitch (or failing that, heading)
> adds fallbacks to the aiTurret's scannode to operate similar to the aimNode

- Engine/source/console/compiledEval.cpp
- Engine/source/console/returnBuffer.cpp
- Engine/source/console/returnBuffer.h
- Engine/source/console/stringStack.cpp
- Engine/source/console/stringStack.h
Try this in devhead:
echo(1, 3);
Notice how `ConsoleValueRef::getStringValue` gets the same buffer as `echo` from `Con::getReturnValue` and causes this to echo `33`? Well it also causes other problems. This fixes that by defining a circular temporary buffer to replace `StringStack::getReturnBuffer`.
Also included is moving most of `StringStack`'s methods into the cpp file.
> Use a circular buffer for getReturnBuffer to prevent buffer cloberring

- Engine/source/platform/async/asyncPacketStream.h
- Engine/source/sfx/sfxSound.cpp
- Engine/source/sfx/sfxSound.h
Note: Only tested with OpenAL.
The method sfxSound.setPosition(time) has some issues:
-The engine method has a miscalculation in some values.
-It doesn't work when the sound is stopped (so you can't modify the time before play).
-It doesn't work at all for files longer than 24 seconds that are streaming and looping (if they're shorter than 24 s, internally they're changed to not-streaming -sfxSystem.cpp: ~line 714-).
To check that you need a datablock SFXProfile with looping and streaming like:
datablock SFXProfile(SoundLength31sLS)
{
filename = "data/sfxSetPosTest/scripts/atime_31s";
description = AudioMusicLoop2D;
};
With that datablock loaded you create the sound with:
$sound_object = sfxCreateSource(SoundLength31sLS);
Then you can test various things like:
$sound_object.play(); …
> Changes for SFXSound::setPosition(time)

- Engine/source/gfx/D3D11/gfxD3D11Device.cpp
Using DXGI_MODE_SCALING_UNSPECIFIED will result in a scaling of widescreen resolutions with a width:height ratio of 16:9 or 16:10 on 4:3 ratio displays, changing the resolution to the next available 4:3 resolution, causing distortion of the view. Changing DXGI_MODE_SCALING_UNSPECIFIED to DXGI_MODE_SCALING_CENTERED will prevent this behavior, resulting in a correct display of these widescreen resolutions.
> Allow correct display of widescreen resolutions (16:9 and 16:10 ratio) on a 4:3 ratio display

- Templates/Full/game/tools/worldEditor/scripts/EditorGui.ed.cs
The change was made to the function that is executed when entering the world editor. The boolean variable for first person shooter was set to true, since the camera always defaults to first person on entering the world editor. On setting this boolean variable to be true, the correct camera setting will always be displayed on entering the world editor. This does not affect other camera labels.
> Fix for bug #1975
