GarageGames/Torque3D

- Engine/source/gfx/gl/gfxGLUtils.h
Fix bad performance on OpenGL.
Related with #1125
> Remove a get* OpenGL function causing CPU-GPU sync point.

- Engine/source/gui/editor/guiEditCtrl.cpp
> Fix changes to moveSelection API

- Templates/Empty/source/torqueConfig.h
- Templates/Full/source/torqueConfig.h
- Tools/CMake/torqueConfig.h.in
- Tools/dae2dts/source/torqueConfig.h
> Fix torqueConfig.h TORQUE_FRAME_SIZE.

- Templates/Empty/game/shaders/common/gl/cloudLayerP.glsl
- Templates/Full/game/shaders/common/gl/cloudLayerP.glsl
> cloudlayer hdr packing

- Engine/source/app/net/serverQuery.cpp
looks like a copypasta slip up.
> extra entry in DefineConsoleFunction( queryMasterServer

- Engine/source/platformMac/macCarbMath.cpp
- Engine/source/platformX86UNIX/x86UNIXMath.cpp
> Add math control state functions for intel

- Engine/source/math/test/mMatrixTest.cpp
> proper fix for https://github.com/GarageGames/Torque3D/issues/1197

- Engine/source/environment/scatterSky.cpp
little typo and testing the pull request =)
> little typo

- Engine/source/shaderGen/GLSL/pixSpecularGLSL.cpp
- Engine/source/shaderGen/GLSL/pixSpecularGLSL.h
- Engine/source/shaderGen/HLSL/pixSpecularHLSL.cpp
- Engine/source/shaderGen/HLSL/pixSpecularHLSL.h
texcoord connector on the vertexshader to avoid link time error
> bugfix #1066

- Templates/Empty/game/tools/navEditor/main.cs
- Templates/Full/game/tools/navEditor/main.cs
> Default to background navmesh builds

- Engine/source/T3D/fx/explosion.cpp
- Engine/source/T3D/fx/explosion.h
(housekeeping) removal of un-implemented ShockwaveData entries from explosion.
> removal of  un-implemented ShockwaveData entries from explosion.

- Templates/Empty/game/shaders/common/water/gl/waterBasicP.glsl
- Templates/Full/game/shaders/common/water/gl/waterBasicP.glsl
Fix #1127 OpenGL Basic Lighting rendering issues (water issues)
> Fix waterBasicP.glsl for HDR.

- Engine/source/lighting/advanced/glsl/gBufferConditionerGLSL.cpp
- Engine/source/lighting/advanced/hlsl/gBufferConditionerHLSL.cpp
suggested by @LuisAntonRebollo.
> https://github.com/GarageGames/Torque3D/issues/770 resolution 

- Engine/source/lighting/shadowMap/pssmLightShadowMap.cpp
further insurance that shadow split stay within bounds.
> further insurance that shadow split stay within bounds.

- Templates/Full/game/scripts/client/init.cs
this is only present in the full template.
Resubmission of #1253 - @eightyeight
> Two equal lines in init.cs

- Engine/source/T3D/fps/guiShapeNameHud.cpp
stops names showing through statics
> stops names showing through statics

- Templates/Full/game/art/forest/managedItemData.cs
- Templates/Full/game/levels/Outpost.mis
> Case-sensitive filenames for Linux

- Engine/source/scene/sceneContainer.cpp
> Add more info to fatal assert in SceneContainer

- Templates/Full/game/levels/Outpost.mis
> Corrected another filename case

- Engine/source/core/util/str.cpp
- Engine/source/core/util/str.h
- Engine/source/forest/forest.cpp
Add static String::isEmpty(const char*) method and use it to verify path for Forest::saveDataFile() is not empty.  Personally not a fan of the old, free-floating dStrBlahBlah functions - I think they would be easier accessed (and remembered) as String::BlahBlah() static methods, especially since intellisense will help you out this way.
This is preferable to creating a String from the const char* and then asking the new string if it's empty.
Consider it an "improvement" on https://github.com/GarageGames/Torque3D/pull/1295
> Add static String::isEmpty(const char*) method

- Engine/source/terrain/terrRender.cpp
Fixed a issue with the terrain blending having hard-edges.
> Fixed a issue with the terrain blending having hard-edges.

- Engine/source/console/engineTypeInfo.h
- Engine/source/console/simObjectRef.h
- Engine/source/core/module.h
- Engine/source/core/util/rawData.h
- Engine/source/core/util/tUnmanagedVector.h
- Engine/source/gfx/gfxVertexBuffer.h
- Engine/source/platform/async/asyncPacketQueue.h
- Engine/source/platform/async/asyncPacketStream.h
- Engine/source/platform/threads/threadPoolAsyncIO.h
- Engine/source/scene/culling/sceneCullingVolume.h
- Engine/source/sfx/sfxCommon.h
- Engine/source/sfx/sfxDevice.cpp
> Fixed some random gcc's -Wreorder warnings

- Engine/source/T3D/turret/turretShape.cpp
from 64 bits per turret to 14 similar to player. they add up.
> reduces rotation transmission size 

- Templates/Empty/game/art/ribbons/ribbons.cs
- Templates/Empty/game/tools/worldEditor/gui/objectBuilderGui.ed.gui
- Templates/Full/game/art/ribbons/ribbons.cs
- Templates/Full/game/tools/worldEditor/gui/objectBuilderGui.ed.gui
This lets you create ribbons from the editors easily for experimentation purposes. See screenshot [here](http://torque3d.wdfiles.com/local--files/scripter:creating-ribbons/ribbon.png).
> Ribbons in the editors

- Engine/source/windowManager/sdl/sdlWindow.cpp
- Engine/source/windowManager/sdl/sdlWindow.h
- Engine/source/windowManager/sdl/sdlWindowMgr.cpp
see https://github.com/GarageGames/Torque3D/issues/1367 for report
> sdl2 mouse wheel scrolling 

- Engine/source/gui/editor/guiMenuBar.cpp
- Engine/source/gui/editor/guiMenuBar.h
- Engine/source/platformSDL/menus/menuBarSDL.cpp
- Templates/Empty/game/tools/gui/guiPlatformGenericMenubar.ed.gui
- Templates/Empty/game/tools/gui/profiles.ed.cs
- Templates/Full/game/tools/gui/guiPlatformGenericMenubar.ed.gui
- Templates/Full/game/tools/gui/profiles.ed.cs
This resolves menu order, cleanup and close/re-open issues, as well as crashes on close.
It also modifies the look slightly to look closer to the windows menubar to keep a cohesive look regardless of platform.
> Fixes the menubar functionality when using SDL.

- Engine/source/shaderGen/GLSL/bumpGLSL.cpp
- Engine/source/terrain/glsl/terrFeatureGLSL.cpp
- Templates/Empty/game/shaders/common/gl/torque.glsl
- Templates/Full/game/shaders/common/gl/torque.glsl
Adds the OGL side of #719. redoing it to make sure the PR history is clean.
> Companion PR to #719

- Engine/source/T3D/decal/decalManager.cpp
Have an attempt work with the many (kilo)meters of decals.
> Fixed a chaotic crash when indices or vertices of decals exceeds the fixed limits

- Engine/lib/libvorbis/lib/codebook.c
- Engine/source/console/consoleFunctions.cpp
- Engine/source/console/typeValidators.cpp
- Engine/source/gfx/gFont.cpp
- Engine/source/gui/containers/guiContainer.cpp
- Engine/source/gui/containers/guiScrollCtrl.cpp
- Engine/source/gui/containers/guiTabBookCtrl.cpp
- Engine/source/gui/controls/guiConsoleTextCtrl.cpp
- Engine/source/gui/controls/guiMLTextCtrl.cpp
- Engine/source/gui/controls/guiTextEditCtrl.cpp
- Engine/source/gui/core/guiControl.cpp
- Engine/source/gui/editor/guiMenuBar.cpp
- Engine/source/gui/editor/guiShapeEdPreview.cpp
- Engine/source/gui/utility/guiMouseEventCtrl.cpp
- Engine/source/gui/utility/guiMouseEventCtrl.h
- Engine/source/math/mMatrix.cpp
- Engine/source/math/mPoint3.h
- Engine/source/math/mQuat.cpp
- Engine/source/math/mQuat.h
- Engine/source/platformWin32/winFileio.cpp
- Engine/source/scene/sceneContainer.cpp
- Engine/source/scene/sceneObject.cpp
Companion PR to #1182
It all seems to work fine, just needs this correction to avoid the current conflict
> Monkey pr w mergefix

- Engine/source/console/dynamicTypes.h
- Engine/source/console/enginePrimitives.h
- Engine/source/console/engineStructs.h
- Engine/source/console/engineTypeInfo.h
- Engine/source/console/engineTypes.h
https://msdn.microsoft.com/en-us/library/y775w13y.aspx?f=255&MSPPError=-2147217396 violations
> partly addresses C4946 warnings

- Templates/Empty/game/core/scripts/gui/messageBoxes/messageBox.ed.cs
Companion PR to #1398 to add the change to the Empty template as well.
> Companion PR to 1398

- Engine/source/gui/controls/guiTextEditCtrl.cpp
see https://github.com/GarageGames/Torque3D/issues/1408
> void GuiTextEditCtrl::execConsoleCallback() reversion

- Engine/source/windowManager/sdl/sdlWindow.cpp
- Engine/source/windowManager/sdl/sdlWindow.h
- Engine/source/windowManager/windowInputGenerator.cpp
Corrects input issues when typing into text fields and it bleeding through to player inputs.
> SDL Textbox bleedthrough inputs fix

- Engine/source/gfx/gl/gfxGLShader.cpp
> remove GL_EXT_gpu_shader4

- Engine/source/environment/meshRoad.cpp
> hooks meshroads up to the material system for castrays 

- Engine/source/gui/core/guiControl.cpp
http://i.imgur.com/fB44GBl.png
> The TypeCommand type brings up a full notepad-esque interface.

- Tools/CMake/libraries/libbullet.cmake
- Tools/CMake/modules/module_bullet.cmake
verified extract from https://github.com/GarageGames/Torque3D/pull/1146
> bullet module

- Engine/source/environment/waterObject.cpp
https://github.com/GarageGames/Torque3D/issues/1458
> removes StaticObjectType flag from water objects.

- Engine/source/T3D/decal/decalData.cpp
Credit for this one goes to @lukaspj
> corrects ghosted decal datablock lookup flaw

- Engine/source/console/consoleObject.h
A new pull request for the one I had accidentally closed previously.
> Fix TinyXML Build errors

- Engine/source/platformWin32/winFileio.cpp
Fix for the directory scan for modules so it doesn't trim off characters in the path.
> Recurse dump directories fix

- Engine/source/core/color.h
- Engine/source/math/mPoint2.h
- Engine/source/math/mPoint3.h
with multi-element classes
Also includes his magnitude and normalize safe alts
> credit to @MusicMonkey5555 for spotting. asserts for Div/NULLs 

- Engine/source/core/stream/stream.cpp
resolves first issue in
https://github.com/GarageGames/Torque3D/issues/1515#issuecomment-184446719
> vsprintf replacement with engine vairant

- Engine/source/gfx/sim/debugDraw.cpp
- Engine/source/gfx/sim/debugDraw.h
DirectionLine, OutlinedText, Capsule
> From Dušan Jocić: additional debugdraw entries. 

- Engine/source/T3D/assets/ShapeAsset.h
- Engine/source/core/stream/stream.cpp
- Engine/source/gfx/gfxDevice.cpp
- Engine/source/math/mathUtils.cpp
- Engine/source/persistence/taml/fsTinyXml.cpp
- Engine/source/persistence/taml/fsTinyXml.h
- Engine/source/persistence/taml/xml/tamlXmlParser.h
- Engine/source/persistence/taml/xml/tamlXmlReader.cpp
- Engine/source/persistence/taml/xml/tamlXmlWriter.cpp
- Engine/source/platformMac/macCarbFileio.mm
- Engine/source/platformX86UNIX/x86UNIXFileio.cpp
for linux and OSX. Correct a couple of warnings and errors preventing builds on linux.
> Fix case sensitivity and Platform::fileDelete

- Templates/Empty/game/core/main.cs
- Templates/Empty/game/core/scripts/client/canvas.cs
- Templates/Full/game/core/main.cs
- Templates/Full/game/core/scripts/client/canvas.cs
"-fullscreen" and "-windowed" were not working properly. This fixes that for Full and Empty templates.
> fullscreen and windowed mode cli fix

- Engine/source/app/net/tcpObject.cpp
- Engine/source/app/net/tcpObject.h
Added several little additions to the TCPObject such as sending a file, callbacks for when everything is finished, and extra script methods.
> Tcp additions

- Engine/source/platform/profiler.cpp
To be honest, can't remember how I was intending to fix that, but this one's causing it to fail to profile twice in a row, so kill it with fire.
> partial reversion for #1333

- Engine/source/T3D/aiPlayer.cpp
- Engine/source/T3D/aiPlayer.h
- Engine/source/T3D/player.cpp
- Engine/source/T3D/shapeBase.cpp
- Engine/source/T3D/shapeBase.h
Reviewed and corrected version of #481 PR.
It uses now signed integer for storing poses enum bits.
> Steve Acaster's Ai Poses

- Engine/source/app/game.cpp
- Engine/source/console/consoleFunctions.cpp
- Engine/source/console/consoleFunctions.h
- Engine/source/core/strings/stringFunctions.h
- Engine/source/core/util/str.cpp
- Engine/source/core/util/str.h
- Engine/source/math/mConsoleFunctions.cpp
- Engine/source/math/mathTypes.cpp
mRound has been restored for incompatibility issue with our scripts they're using it.
> [CLONE] More consolefunctions #1143

- Templates/Empty/game/tools/gui/openFileDialog.ed.cs
- Templates/Full/game/tools/gui/openFileDialog.ed.cs
Added some extra parameters to open file dialogue and added a check to findConstructor so it doesn't throw errors.
> Improved file open dialogue

- Engine/source/console/consoleObject.h
- Engine/source/console/engineTypeInfo.h
Conflicts have been resolved.
Original PR: #1206
> [CLONE] Add support for abstract ConObjects

- Engine/source/console/console.cpp
- Engine/source/console/simSet.cpp
Anis and me managed to fix this in a proper way than: #1508
> Fix crash callonchildren

- Engine/source/scene/simPath.cpp
- Engine/source/scene/simPath.h
Includes a vertex type formatting fix for the SimPath change to make it compatible with DX11.
> Fix for SimPath to make DX11 compatible.

- Engine/source/gfx/D3D11/screenshotD3D11.cpp
I'm not even going to say anything lol
> ScreenShotD3D11 delete fix.

- Templates/Empty/game/core/scripts/client/lighting/advanced/shaders.cs
- Templates/Full/game/core/scripts/client/lighting/advanced/shaders.cs
Implements #1590 with the changes duplicated in the Empty template as well.
> missing samplerstate configurations with empty

- Engine/source/gfx/gl/gfxGLCircularVolatileBuffer.h
- Engine/source/gfx/gl/gfxGLDevice.cpp
- Engine/source/gfx/gl/gfxGLShader.cpp
- Engine/source/gfx/gl/gfxGLStateBlock.cpp
- Engine/source/gfx/gl/gfxGLTextureManager.cpp
- Engine/source/gfx/gl/gfxGLTextureObject.cpp
Please check to make sure I put these in the right places. There's a couple that I had to leave out from the D3D9 ones because they didn't make sense, but I tried to match as many as I could.
> Added missing OpenGL profiling blocks.

- Engine/source/materials/materialFeatureTypes.cpp
- Engine/source/shaderGen/GLSL/shaderFeatureGLSL.cpp
- Engine/source/shaderGen/HLSL/shaderFeatureHLSL.cpp
applies it adaptively based on defered or forward lit context
> Fixes vertcolor code insertion order, and 

- Templates/Empty/game/tools/shapeEditor/scripts/shapeEditor.ed.cs
- Templates/Empty/game/tools/worldEditor/scripts/editors/creator.ed.cs
- Templates/Full/game/tools/shapeEditor/scripts/shapeEditor.ed.cs
- Templates/Full/game/tools/worldEditor/scripts/editors/creator.ed.cs
Bug space folder in scene tree
Fix by David Robert Pemberton
https://www.garagegames.com/community/blogs/view/22295
Before, the space break up the folder in to 2 folders.
Bug fix: Now you can see the folder "soldier actor" as one folder.
> Bug space folder in scene tree 2

- Engine/source/shaderGen/HLSL/accuFeatureHLSL.cpp
Fix for the accumulation shadergen failing to compile under DX11.
> DX11 accumulation shadergen fix.

- Engine/source/T3D/aiPlayer.cpp
- Engine/source/navigation/navPath.cpp
just a typo in aiplayer and navpath
> typo "tomove" to "to move"

- Engine/source/T3D/staticShape.h
- Templates/Full/game/art/datablocks/player.cs
@Azaezel  http://forums.torque3d.org/viewtopic.php?f=11&t=685
> Cleanup unused functions

- Templates/Empty/game/tools/shapeEditor/scripts/shapeEditor.ed.cs
- Templates/Full/game/tools/shapeEditor/scripts/shapeEditor.ed.cs
> corrects https://github.com/GarageGames/Torque3D/issues/1273 

- Engine/source/T3D/lightBase.cpp
- Engine/source/T3D/objectTypes.h
- Engine/source/lighting/lightManager.cpp
- Engine/source/scene/sceneManager.cpp
- Engine/source/scene/sceneManager.h
Makes point and spot lights be correctly culled with zoning like other objects.
> Corrects culling of point/spot lights

- Templates/Empty/game/core/scripts/server/defaults.cs
- Templates/Full/game/core/scripts/server/defaults.cs
Change "the FPS starter kit" for "Torque3D".
> Corrected "Pref::Server::ConnectionError" description.

- Engine/source/ts/tsCollision.cpp
- corrects issues with awesomium and the guionobject resources relating to WYSIWYG casts.
> raycast division safety 

- Engine/source/T3D/tsStatic.cpp
Fix bug  Bitstream.cpp Fatal Out of range read #1664 by @Areloch
> Fix bug #1664 by @Areloch

- Engine/source/T3D/aiPlayer.cpp
- Engine/source/T3D/aiPlayer.h
Fix AIPlayer aim to target. This removes the problem of bad aim to the target.
http://forums.torque3d.org/viewtopic.php?f=11&t=673&p=5718#p5718
> Correct AIPlayer aim.

- Engine/source/gui/controls/guiAnimBitmapCtrl.cpp
- Engine/source/gui/controls/guiAnimBitmapCtrl.h
- works similar to the particle animation system. feed it x and y for how many frames in a spritesheet, and let her run.
also supports:
either specific frames, a range to play, or a mix (string)
fps specification, (int)
loop, (bool)
pausing, (bool)
reverse (bool)
play (bool)
and has callbacks for onLoop, onCompleted, and onFrame (index and actual frame passed along)
> new: guiAnimBitmapCtrl

- Engine/source/gui/editor/guiPopupMenuCtrl.cpp
- Engine/source/gui/editor/guiPopupMenuCtrl.h
- Engine/source/platformSDL/menus/guiPlatformGenericMenuBar.h
- Engine/source/platformSDL/menus/menuBarSDL.cpp
- Engine/source/platformSDL/menus/popupMenuSDL.cpp
- Templates/Full/game/tools/worldEditor/scripts/EditorGui.ed.cs
Implements the right-mouse popup menus in the editor for SDL to make it match to Windows' platform handling.
> Sdl popup menus

- Engine/source/gui/controls/guiAnimBitmapCtrl.cpp
- Engine/source/gui/controls/guiBitmapBarCtrl.cpp
- Engine/source/gui/controls/guiBitmapCtrl.cpp
- Engine/source/gui/controls/guiBitmapCtrl.h
guibitmapctrl, guibitmapbarctrl, guianimbitmapctrl (and guicrosshairhud by way of inheritance)
> adds bitmap coloration to: 

- Engine/source/i18n/lang.cpp
- Engine/source/i18n/lang.h
http://forums.torque3d.org/viewtopic.php?f=12&t=642&hilit=localization
> localization augmentations via rlranft RE: 

- Engine/source/T3D/fx/particleEmitter.cpp
- Templates/Full/game/tools/particleEditor/ParticleEditor.ed.gui
- Templates/Full/game/tools/particleEditor/particleParticleEditor.ed.cs
windCoefficient, animateTexture, framesPerSec, animTexFrames*, animTexTiling
*at time of writing, it will read and write this entry to disk, but will not update in realtime. via the handcoded editing tool.
> exposes several datablock entries to the particle editor gui subsystem

- Engine/source/navigation/navMesh.cpp
don't try to read 0 length buffers
> navmesh file load error-fix

- Engine/source/core/ogg/oggTheoraDecoder.cpp
- Engine/source/core/ogg/oggTheoraDecoder.h
- Engine/source/shaderGen/GLSL/shaderFeatureGLSL.cpp
- Engine/source/shaderGen/GLSL/shaderFeatureGLSL.h
- Engine/source/shaderGen/GLSL/shaderGenGLSLInit.cpp
- Engine/source/shaderGen/HLSL/shaderFeatureHLSL.cpp
- Engine/source/shaderGen/HLSL/shaderFeatureHLSL.h
- Engine/source/shaderGen/HLSL/shaderGenHLSLInit.cpp
('identifier' : local variable is initialized but not referenced)
> adresses C4189 warnings 

- Engine/source/T3D/player.cpp
fix  for this issue https://github.com/GarageGames/Torque3D/issues/1709
> fixes footsteps missing when no impactSoundId

- Engine/source/T3D/accumulationVolume.cpp
- Engine/source/T3D/levelInfo.cpp
- Engine/source/T3D/levelInfo.h
- Engine/source/T3D/shapeBase.cpp
- Engine/source/T3D/tsStatic.cpp
* overidden if an object's origin is in an accumulationVolume.
> level-wide accumulation assignment 

- Engine/source/T3D/physics/physicsShape.cpp
fix #1689
This fix a bug when you try to create a new physics shape datablock.
> fix create datablock for physicsshapes.

- Engine/source/T3D/shapeBase.cpp
this https://github.com/GarageGames/Torque3D/pull/1725#issuecomment-238079691
> added path @dottools

- Engine/source/T3D/physics/physicsShape.cpp
This PR is suggested by @rextimmy to replace this PR #1736
both will allow add physicShape datablock https://drive.google.com/file/d/0B9GUwtDHCp_ed000bndXYW9CS1k
> replace fix #1736 for add physicShape datablock from the editor

- Engine/source/windowManager/sdl/sdlSplashScreen.cpp
- Engine/source/windowManager/sdl/sdlWindowMgr.cpp
Implements the splash screen window to the SDL platform stuff.
> Implements the splash screen window to the SDL platform stuff.

- Templates/Full/game/shaders/common/postFx/fogP.hlsl
- Templates/Full/game/shaders/common/postFx/gl/fogP.glsl
so it falls within the same scale system as ambient and the like
> linearizes fog color 

- Templates/Empty/game/tools/worldEditor/scripts/EditorGui.ed.cs
- Templates/Full/game/tools/worldEditor/scripts/EditorGui.ed.cs
Fixes the Toggle Children Lock and Toggle Children Hidden options in the editor context popup menu.
> Fixes the Toggle Children Lock and Toggle Children Hidden options

- Engine/lib/libogg/CHANGES
- Engine/lib/libogg/include/ogg/config_types.h.in
- Engine/lib/libogg/include/ogg/os_types.h
- Engine/lib/libogg/src/bitwise.c
- Engine/lib/libogg/src/framing.c
- Tools/CMake/libraries/libogg.cmake
libogg update and also added fix #1293
> Update libogg to 1.3.2

- Engine/source/gfx/gfxDevice.cpp
- Templates/Full/game/core/scripts/client/postFx/GammaPostFX.cs
- Templates/Full/game/core/scripts/client/postFx/fog.cs
- Templates/Full/game/core/scripts/client/postFx/hdr.cs
- Templates/Full/game/core/scripts/client/renderManager.cs
until we have a proper srgb compatible buffer to minimize that with, we'll have to settle for 16F looks like
> banding: conforms misbehaving postfx to the hdr buffer format

- Engine/source/math/mEase.h
self modifying variables inside equations made clang unhappy. 
basis: http://gizma.com/easing/#circ1
> retooled circular ease methods

- Templates/Empty/game/shaders/common/water/gl/waterP.glsl
- Templates/Empty/game/shaders/common/water/waterP.hlsl
- Templates/Full/game/shaders/common/water/gl/waterP.glsl
- Templates/Full/game/shaders/common/water/waterP.hlsl
Corrects the specular handling as per Richard's suggestion in #1783
> Corrects the specular handling as per Richard's suggestion in #1783

- Engine/source/windowManager/sdl/sdlSplashScreen.cpp
Also adds a sanity check in the event a splash image isn't found.
> Also adds a sanity check in the event a splash image isn't found.

- Engine/source/app/mainLoop.cpp
- Engine/source/windowManager/sdl/sdlWindow.cpp
Needed a false in there, and a very useless #ifdef
> Fix SDL/Mac report going into the background

- Engine/source/T3D/physics/bullet/btCollision.cpp
Fix from @Lopuska 's PhysicsGMKRefactor branch!
> Fixes Bullet not supporting holes in terrain.

- LICENSE.md
- README.md
> readme update

- Engine/source/core/color.h
- Engine/source/gui/buttons/guiSwatchButtonCtrl.cpp
- Engine/source/gui/buttons/guiSwatchButtonCtrl.h
- Engine/source/gui/controls/guiColorPicker.cpp
- Engine/source/gui/controls/guiColorPicker.h
- Templates/Empty/game/tools/gui/colorPicker.ed.gui
- Templates/Full/game/tools/gui/colorPicker.ed.gui
dependency from @rextimmy: tolinear and togamma for color+lumnance.
partly addresses https://github.com/GarageGames/Torque3D/issues/1870
full followup (cleanup and consistency) pending 4.0
> colorPicker/swatch srgb display.

- Engine/source/gfx/gl/gfxGLDevice.cpp
- Engine/source/gfx/gl/gfxGLDevice.h
- Engine/source/gfx/gl/tGL/tGL.cpp
- Engine/source/gfx/gl/tGL/tWGL.h
- Engine/source/gfx/gl/win32/gfxGLDevice.win.cpp
- Engine/source/platformSDL/sdlPlatformGL.cpp
- Engine/source/platformWin32/WinPlatformGL.cpp
Enables setting vsync for OpenGL without needing to re-start the app.
> OpenGL vsync fixes.

- Templates/Empty/game/tools/worldEditor/scripts/menus.ed.cs
- Templates/Full/game/tools/worldEditor/scripts/menus.ed.cs
This tool display a list of all game objects, SimObject, SimGroup, and SimSet instances
> added torque SimView tool

- Engine/source/T3D/shapeImage.cpp
fix https://github.com/GarageGames/Torque3D/issues/696
> fix issue #696

- Engine/source/T3D/physics/bullet/btBody.cpp
- Engine/source/T3D/physics/bullet/btBody.h
- Engine/source/T3D/physics/physicsBody.h
- Engine/source/T3D/physics/physicsShape.cpp
- Engine/source/T3D/physics/physicsShape.h
- Engine/source/T3D/physics/physx3/px3Body.cpp
- Engine/source/T3D/physics/physx3/px3Body.h
Adds applyTorque console function to PhysicsShape
> PhysicsShape applyTorque function

- Templates/Full/game/art/datablocks/physics.cs
Simple examples of PhysicsShapeData usage for the full template.
> PhysicsShapeData examples

- Engine/source/T3D/staticShape.cpp
Somebody made a typo and didn't test if it compiled before committing...
> Fixed StaticShape onUnmount

- Engine/source/platformPOSIX/posixVolume.cpp
> Call the correct system rename

- Engine/source/renderInstance/renderParticleMgr.cpp
A minor change which caused some issues in my work with C#.
Basically, instead of cleaning up when the LM deactivates, we re-initialize most things. 
This change implements cleanup instead.
> Cleanup when deactivating light manager instead of reinitializing

- Templates/Empty/game/art/gui/mainMenuGui.gui
- Templates/Empty/game/tools/base/utils/inspector.ed.cs
- Templates/Empty/game/tools/guiEditor/gui/guiEditor.ed.gui
- Templates/Empty/game/tools/guiEditor/scripts/guiEditor.ed.cs
- Templates/Empty/game/tools/worldEditor/gui/EditorGui.ed.gui
- Templates/Empty/game/tools/worldEditor/scripts/EditorGui.ed.cs
- Templates/Empty/game/tools/worldEditor/scripts/editor.ed.cs
- Templates/Empty/game/tools/worldEditor/scripts/menus.ed.cs
- Templates/Full/game/art/gui/mainMenuGui.gui
- Templates/Full/game/tools/base/utils/inspector.ed.cs
- Templates/Full/game/tools/guiEditor/gui/guiEditor.ed.gui
- Templates/Full/game/tools/guiEditor/scripts/guiEditor.ed.cs
- Templates/Full/game/tools/worldEditor/gui/EditorGui.ed.gui
- Templates/Full/game/tools/worldEditor/scripts/EditorGui.ed.cs
- Templates/Full/game/tools/worldEditor/scripts/editor.ed.cs
- Templates/Full/game/tools/worldEditor/scripts/menus.ed.cs
Reworks the open/close functions of the gui and world editors so they will properly handle their menubars and toggle between and clean up when closed.
> Fixes editor handling of menubars when opening/closing.

- Templates/Full/game/scripts/client/init.cs
- Templates/Full/game/scripts/gui/optionsDlg.cs
Added vehicle re-mapping functionality for the vehicle movements (forward, backward, brake).
Essentially just added a branched functionality if re-mapped functionality is vehicular without affecting the original functionality. Please let me know if there is anything to change.
> Added gui functionality for vehicle re-mapping as per #950

- Engine/source/windowManager/win32/win32WindowMgr.cpp
> Solves issue with getDesktopResolution and Windows 10 Creator update

- Engine/source/renderInstance/renderDeferredMgr.cpp
As per issue #1998. Credit to @maddin200 for the find.
> Fixes a redundant flag test

- Engine/source/console/scriptObjects.cpp
As per issue #1999. Credit to @maddin200  for the find.
> Cleans up a redundant include.

- Engine/source/lighting/advanced/advancedLightManager.cpp
- Engine/source/lighting/advanced/hlsl/advancedLightingFeaturesHLSL.cpp
- Engine/source/lighting/basic/basicLightManager.cpp
- Engine/source/renderInstance/renderDeferredMgr.cpp
- Engine/source/renderInstance/renderDeferredMgr.h
- Engine/source/renderInstance/renderImposterMgr.cpp
- Engine/source/renderInstance/renderImposterMgr.h
- Engine/source/renderInstance/renderParticleMgr.cpp
- Engine/source/terrain/terrCellMaterial.cpp
- Engine/source/terrain/terrCellMaterial.h
Missed a few conversions of prepass to deferred in the engine side. This should get the remainder.
> Catches the remaining prepass to deferred changes on the engine side.

- Templates/BaseGame/game/tools/shapeEditor/gui/shapeEdPropWindow.ed.gui
> node filter for shape editor

- Engine/source/gfx/sim/cubemapData.cpp
- Engine/source/gfx/sim/cubemapData.h
This add supports for single file dds cubemaps for the CubemapData class. An example skybox & material file here if anyone needs one for testing https://drive.google.com/open?id=0B0tHSJ8eQYh6ejVuWmdSd3lGVWc
> DDS CubemapData support

- Engine/source/T3D/gameFunctions.cpp
- Engine/source/T3D/gameFunctions.h
- Engine/source/lighting/advanced/advancedLightBinManager.cpp
- Engine/source/lighting/advanced/advancedLightBinManager.h
Includes a fix to get lights to render more correctly in the reflection pass. Also includes a helper function to force a render from a passed in transform and frustum.
> Fix light rendering in reflections.

- Engine/source/terrain/glsl/terrFeatureGLSL.cpp
- Engine/source/terrain/hlsl/terrFeatureHLSL.cpp
This PR seeks to adress #2050 .
In the image below, you can see the difference in results, before this PR is to the right, and after is to the left.
> Fix for terrain detail color blending post-linearization

- Engine/source/core/color.h
This fixes a pretty ordinary mistake i made with the original color changes.
> ColorI::fromLinear fix

- Templates/BaseGame/game/tools/navEditor/main.cs
- Templates/Full/game/tools/navEditor/main.cs
something that was on my todo-list for some time =)
very useful to tweak the options in a easy way.
http://forums.torque3d.org/viewtopic.php?f=12&t=161&start=10#p1498
http://forums.torque3d.org/viewtopic.php?f=12&t=161&start=20#p1547
> add navPath from inside of WEditor

- Engine/source/sqlite/SQLiteObject.cc
- Engine/source/sqlite/SQLiteObject.h
- Engine/source/sqlite/sqlite3.h
- Engine/source/sqlite/sqlite3ext.h
- Tools/CMake/modules/module_sqlite.cmake
I have used the updated version of Chris Calef work to add this.
I have added the cmake file so that you can choose to have it or not
> SQLite Integration 

- README.md
again :) trying to update the broken documentation link.... 
- related https://github.com/GarageGames/Torque3D/pull/1662
- related https://github.com/GarageGames/Torque3D/issues/1875
> update broken documentation link

- Engine/source/gfx/D3D11/gfxD3D11StateBlock.cpp
- Engine/source/gfx/gl/gfxGLStateBlock.cpp
- Engine/source/math/mathUtils.cpp
Also corrects the following problems:
OpenGL glPolygonOffset values
Direct3D11 DepthBias values
This also fixes #1666
> Corrects OpenGL projection matrix

- Engine/source/windowManager/sdl/sdlWindowMgr.cpp
Enables SDL's ability to drag and drop files onto the game window and have it call back into script for handling.
> Enables SDL's ability to drag and drop files onto the game window

- Engine/source/math/mRotation.cpp
Tweaks the asMatrixF for RotationF, as well as exposes additional console methods for rotation manipulation
> Tweaks the asMatrixF for RotationF

- Engine/source/assets/assetManager.cpp
- Engine/source/assets/assetManager.h
- Engine/source/assets/autoloadAssets.cpp
- Engine/source/assets/autoloadAssets.h
- Engine/source/module/moduleDefinition.h
Adds the ability to define types of assets to be auto-loaded when the module is initialized.
> Adds the ability to define types of assets to be auto-loaded

- Engine/source/T3D/components/component.cpp
- Engine/source/T3D/components/component.h
- Engine/source/T3D/components/render/meshComponent.cpp
- Engine/source/T3D/entity.cpp
- Engine/source/T3D/entity.h
Fixes up various parts of the entity and component classes.
> Fixes up various parts of the entity and component classes.

- Engine/source/scene/sceneObject.cpp
- Engine/source/scene/sceneObject.h
Enables setting the forward vector of a Scene Object
> Enables setting the forward vector of a Scene Object

- Engine/source/gui/core/guiCanvas.h
Adds a function to get the cursor position in local coords
> Adds a function to get the cursor position in local coords

- Engine/source/afx/util/afxParticlePool_T3D.cpp
Corrects an include's case sensitivity being wrong, causing issues on linux.
> Corrects an include's case sensitivity being wrong

- Engine/lib/nativeFileDialogs/SConstruct
- Engine/lib/nativeFileDialogs/common.h
- Engine/lib/nativeFileDialogs/include/nfd.h
- Engine/lib/nativeFileDialogs/nfd_cocoa.m
- Engine/lib/nativeFileDialogs/nfd_gtk.c
- Engine/lib/nativeFileDialogs/nfd_win.cpp
- Engine/source/platform/nativeDialogs/fileDialog.cpp
Updates Native File Dialogs lib to enable browsing and selecting of folders, instead of just files.
> Updates Native File Dialogs lib to enable folder browsing.

- Engine/source/sim/netObject.cpp
Adds a engine method to clear the scopeAlways flag on netObjects
> Adds a engine method to clear the scopeAlways flag on netObjects

- Engine/source/lighting/advanced/advancedLightManager.cpp
- Engine/source/lighting/advanced/advancedLightManager.h
- Engine/source/lighting/common/projectedShadow.cpp
- Engine/source/lighting/shadowMap/shadowMapManager.cpp
> Fixes for compiling without Basic Lighting

- Engine/lib/collada/src/dae/daeRawResolver.cpp
> Fix for daeRawResolver resource leak

- Templates/BaseGame/game/tools/base/images/materials.cs
- Templates/Full/game/art/skies/Desert_Sky/materials.cs
- Templates/Full/game/art/skies/night/materials.cs
- Templates/Full/game/core/art/skies/blank/materials.cs
- Templates/Modules/FPSGameplay/art/skies/Blank_sky/materials.cs
- Templates/Modules/FPSGameplay/art/skies/Desert_Sky/materials.cs
- Templates/Modules/FPSGameplay/art/skies/night/materials.cs
isSky is no longer used in the engine.
> removed isSky from template sky material files.

- Engine/source/T3D/assets/ShapeAnimationAsset.cpp
- Engine/source/T3D/assets/ShapeAnimationAsset.h
- Engine/source/T3D/assets/ShapeAsset.cpp
- Engine/source/T3D/components/animation/animationComponent.cpp
- Engine/source/ts/collada/colladaImport.cpp
- Templates/BaseGame/game/tools/shapeEditor/scripts/shapeEditorActions.ed.cs
Bugfixes and improvements for the animation component and related asset behavior.
Adds in ability to establish a shape animation asset as being cyclic or blended.
Adds functionality for blended animations to integrated into shapeAssets.
> Bugfixes and improvements for the animation component and related assets

- Engine/source/T3D/assets/ImageAsset.cpp
- Engine/source/T3D/assets/ImageAsset.h
- Engine/source/T3D/assets/LevelAsset.cpp
- Engine/source/T3D/assets/ScriptAsset.cpp
- Engine/source/T3D/components/animation/animationComponent.cpp
- Engine/source/T3D/components/collision/collisionComponent.cpp
- Engine/source/T3D/components/component.cpp
- Engine/source/T3D/components/game/stateMachine.cpp
- Engine/source/T3D/components/game/stateMachine.h
- Engine/source/T3D/components/physics/playerControllerComponent.cpp
- Engine/source/T3D/components/render/meshComponent.cpp
- Engine/source/T3D/entity.cpp
- Engine/source/T3D/entity.h
- Engine/source/T3D/systems/render/meshRenderSystem.cpp
- Engine/source/gui/editor/inspector/entityGroup.cpp
Some code cleanup, tweak and optimizations for assets, entities and components.
> Some code cleanup on assets, entities and components, round 1

- Engine/source/gfx/sim/cubemapData.cpp
- Engine/source/gui/buttons/guiBitmapButtonCtrl.cpp
corrects a couple backend profile assignment mismatches found with @rextimmys debug spew
> companion to #2203: 

- Engine/source/math/mConsoleFunctions.cpp
- Engine/source/math/mMathFn.h
for cycling values to within a given range.
examples of usage would be say, keeping a rotation within 360 degrees, or hitting a tile boundary and resetting the offset
> adds an mWrap and mWrapF method 

- Engine/source/main/main.cpp
tell switchable graphics supported systems that they need to use the beefier GPU
> switchable GPU Support

- Templates/BaseGame/game/core/renderManager.cs
- Templates/Full/game/core/scripts/client/renderManager.cs
Includes some renderbin declarations that are needed for AFX that got missed in the original PR.
> Includes some renderbin declarations that are needed for AFX

- Engine/source/ts/tsCollision.cpp
This commit fixes an issue where collision meshes created from primitives in the shape editor are not scaled with the shape. Standard Torque collision does not have this problem. This only affects the meshes built for the physics plugins.
> Sets scale for collision primitives created in the shape editor.
